/**
 * DIVE V3 - Demo Users Setup Script
 * 
 * Creates demo users for presentation with:
 * - 4 users per instance (DEU, USA, FRA, GBR)
 * - Predictable passwords
 * - Pre-configured MFA with predictable OTP codes
 * - Super admin users with super_admin role
 * 
 * Usage:
 *   npm run ts-node backend/src/scripts/setup-demo-users.ts
 * 
 * Demo Credentials:
 *   Users: demo-{instance}-{1-4} (e.g., demo-usa-1)
 *   Password: Demo2025!Secure
 *   OTP Code: 123456 (for demo purposes)
 *   Super Admin: admin-{instance} (e.g., admin-usa)
 */

import KcAdminClient from '@keycloak/keycloak-admin-client';
import axios from 'axios';
import speakeasy from 'speakeasy';
import { execSync } from 'child_process';
import dotenv from 'dotenv';

dotenv.config();

// ============================================
// CONFIGURATION
// ============================================

const INSTANCES = ['DEU', 'USA', 'FRA', 'GBR'] as const;
const REALM = 'dive-v3-broker';
const DEMO_PASSWORD = 'Demo2025!Secure';
// Base32-encoded secret for predictable demo OTP codes
// This secret will generate codes that change every 30 seconds
// For demo purposes, users can use any valid 6-digit code from their authenticator app
// Or use the current code generated by: speakeasy.totp({ secret: DEMO_OTP_SECRET, encoding: 'base32' })
const DEMO_OTP_SECRET = 'DEMO123456789012345678901234567890'; // Base32 format
const SUPER_ADMIN_PASSWORD = 'Admin2025!Secure';

// Instance configurations
const INSTANCE_CONFIG: Record<string, { url: string; container?: string; remote?: boolean }> = {
    'USA': {
        url: process.env.KEYCLOAK_URL || 'http://localhost:8080',
        container: 'dive-v3-keycloak'
    },
    'FRA': {
        url: process.env.KEYCLOAK_FRA_URL || 'http://localhost:8080',
        container: 'dive-v3-keycloak-fra'
    },
    'GBR': {
        url: process.env.KEYCLOAK_GBR_URL || 'http://localhost:8080',
        container: 'dive-v3-keycloak-gbr'
    },
    'DEU': {
        url: process.env.KEYCLOAK_DEU_URL || 'https://prosecurity.biz',
        remote: true
    }
};

// Clearance levels for demo users
const CLEARANCE_LEVELS = {
    '1': { clearance: 'UNCLASSIFIED', coi: [] },
    '2': { clearance: 'CONFIDENTIAL', coi: [] },
    '3': { clearance: 'SECRET', coi: ['NATO'] },
    '4': { clearance: 'TOP_SECRET', coi: ['FVEY', 'NATO-COSMIC'] }
};

// ============================================
// UTILITY FUNCTIONS
// ============================================

async function getAdminPassword(instance: string): Promise<string> {
    const envVar = `KEYCLOAK_ADMIN_PASSWORD_${instance}`;
    const password = process.env[envVar] || process.env.KEYCLOAK_ADMIN_PASSWORD;
    
    if (password && password !== 'admin') {
        return password;
    }

    try {
        const secretName = `dive-v3-keycloak-${instance.toLowerCase()}`;
        const result = execSync(
            `gcloud secrets versions access latest --secret=${secretName} --project=dive25 2>/dev/null`,
            { encoding: 'utf-8' }
        );
        if (result.trim()) {
            return result.trim();
        }
    } catch (error) {
        // GCP not available, use default
    }

    return 'DivePilot2025!SecureAdmin';
}

async function getAdminToken(keycloakUrl: string, instance: string): Promise<string> {
    const adminPassword = await getAdminPassword(instance);
    const tokenUrl = `${keycloakUrl}/realms/master/protocol/openid-connect/token`;
    
    const response = await axios.post(
        tokenUrl,
        new URLSearchParams({
            grant_type: 'password',
            client_id: 'admin-cli',
            username: 'admin',
            password: adminPassword
        }),
        { headers: { 'Content-Type': 'application/x-www-form-urlencoded' } }
    );

    return response.data.access_token;
}

function createKcAdminClient(keycloakUrl: string, instance: string): KcAdminClient {
    return new KcAdminClient({
        baseUrl: keycloakUrl,
        realmName: 'master'
    });
}

async function authenticateKcClient(client: KcAdminClient, instance: string): Promise<void> {
    const adminPassword = await getAdminPassword(instance);
    await client.auth({
        username: 'admin',
        password: adminPassword,
        grantType: 'password',
        clientId: 'admin-cli'
    });
}

// ============================================
// USER CREATION
// ============================================

async function createDemoUser(
    client: KcAdminClient,
    instance: string,
    level: string,
    adminToken: string,
    keycloakUrl: string
): Promise<void> {
    const username = `demo-${instance.toLowerCase()}-${level}`;
    const config = CLEARANCE_LEVELS[level as keyof typeof CLEARANCE_LEVELS];
    
    console.log(`  Creating user: ${username} (${config.clearance})`);

    try {
        // Check if user exists
        const existingUsers = await client.users.find({
            realm: REALM,
            username,
            exact: true
        });

        let userId: string;

        if (existingUsers && existingUsers.length > 0) {
            userId = existingUsers[0].id!;
            console.log(`    User exists, updating...`);
            
            // Update user
            await client.users.update(
                { realm: REALM, id: userId },
                {
                    enabled: true,
                    email: `${username}@dive-demo.example`,
                    firstName: 'Demo',
                    lastName: `${instance}-${level}`,
                    attributes: {
                        clearance: [config.clearance],
                        countryOfAffiliation: [instance],
                        uniqueID: [username],
                        userType: ['military'],
                        organization: [`${instance} Defense`],
                        organizationType: ['GOV'],
                        pilot_user: ['true'],
                        clearance_level: [level]
                    }
                }
            );
        } else {
            // Create new user
            const newUser = await client.users.create({
                realm: REALM,
                username,
                enabled: true,
                email: `${username}@dive-demo.example`,
                firstName: 'Demo',
                lastName: `${instance}-${level}`,
                attributes: {
                    clearance: [config.clearance],
                    countryOfAffiliation: [instance],
                    uniqueID: [username],
                    userType: ['military'],
                    organization: [`${instance} Defense`],
                    organizationType: ['GOV'],
                    pilot_user: ['true'],
                    clearance_level: [level]
                }
            });
            userId = newUser.id!;
            console.log(`    User created: ${userId}`);
        }

        // Set password
        await client.users.resetPassword({
            realm: REALM,
            id: userId,
            credential: {
                temporary: false,
                type: 'password',
                value: DEMO_PASSWORD
            }
        });
        console.log(`    Password set`);

        // Set required action for MFA (CONFIGURE_TOTP for SECRET/CONFIDENTIAL, webauthn for TOP_SECRET)
        const requiredActions = config.clearance === 'TOP_SECRET' 
            ? ['webauthn-register-passwordless']
            : ['CONFIGURE_TOTP'];
        
        await client.users.update(
            { realm: REALM, id: userId },
            { requiredActions }
        );
        console.log(`    Required actions set: ${requiredActions.join(', ')}`);

        // Store OTP secret in Redis for users that need OTP
        if (config.clearance !== 'UNCLASSIFIED' && config.clearance !== 'TOP_SECRET') {
            await storeOTPSecretInRedis(userId, DEMO_OTP_SECRET);
            console.log(`    OTP secret stored in Redis`);
        }

    } catch (error: any) {
        console.error(`    ERROR creating user ${username}:`, error.message);
        throw error;
    }
}

async function createSuperAdminUser(
    client: KcAdminClient,
    instance: string,
    adminToken: string,
    keycloakUrl: string
): Promise<void> {
    const username = `admin-${instance.toLowerCase()}`;
    
    console.log(`  Creating super admin: ${username}`);

    try {
        // Check if user exists
        const existingUsers = await client.users.find({
            realm: REALM,
            username,
            exact: true
        });

        let userId: string;

        if (existingUsers && existingUsers.length > 0) {
            userId = existingUsers[0].id!;
            console.log(`    User exists, updating...`);
        } else {
            const newUser = await client.users.create({
                realm: REALM,
                username,
                enabled: true,
                email: `${username}@dive-demo.example`,
                firstName: 'Admin',
                lastName: instance,
                attributes: {
                    clearance: ['TOP_SECRET'],
                    countryOfAffiliation: [instance],
                    uniqueID: [username],
                    userType: ['administrator'],
                    organization: [`${instance} Defense`],
                    organizationType: ['GOV']
                }
            });
            userId = newUser.id!;
            console.log(`    User created: ${userId}`);
        }

        // Set password
        await client.users.resetPassword({
            realm: REALM,
            id: userId,
            credential: {
                temporary: false,
                type: 'password',
                value: SUPER_ADMIN_PASSWORD
            }
        });
        console.log(`    Password set`);

        // Get super_admin role
        const roles = await client.roles.find({
            realm: REALM,
            roleName: 'super_admin'
        });

        if (roles && roles.length > 0) {
            // Assign super_admin role
            await client.users.addRealmRoleMappings({
                realm: REALM,
                id: userId,
                roles: [roles[0]]
            });
            console.log(`    Super admin role assigned`);
        } else {
            console.warn(`    WARNING: super_admin role not found in realm`);
        }

        // Set required action for MFA
        await client.users.update(
            { realm: REALM, id: userId },
            { requiredActions: ['CONFIGURE_TOTP'] }
        );
        console.log(`    Required actions set: CONFIGURE_TOTP`);

        // Store OTP secret in Redis
        await storeOTPSecretInRedis(userId, DEMO_OTP_SECRET);
        console.log(`    OTP secret stored in Redis`);

    } catch (error: any) {
        console.error(`    ERROR creating super admin ${username}:`, error.message);
        throw error;
    }
}

// ============================================
// OTP SECRET STORAGE (Redis)
// ============================================

async function storeOTPSecretInRedis(userId: string, secret: string): Promise<void> {
    try {
        // Import Redis client dynamically
        const { storePendingOTPSecret } = await import('../services/otp-redis.service');
        
        const stored = await storePendingOTPSecret(userId, secret, 86400 * 365); // 1 year TTL for demo
        
        if (!stored) {
            console.warn(`    WARNING: Could not store OTP secret in Redis for ${userId}`);
        }
    } catch (error: any) {
        console.warn(`    WARNING: Redis not available, skipping OTP secret storage: ${error.message}`);
        // Non-critical for demo setup
    }
}

// ============================================
// TESTING
// ============================================

async function testUserLogin(
    keycloakUrl: string,
    instance: string,
    username: string,
    password: string
): Promise<boolean> {
    try {
        const tokenUrl = `${keycloakUrl}/realms/${REALM}/protocol/openid-connect/token`;
        
        const response = await axios.post(
            tokenUrl,
            new URLSearchParams({
                grant_type: 'password',
                client_id: 'dive-v3-client',
                username,
                password
            }),
            { headers: { 'Content-Type': 'application/x-www-form-urlencoded' } }
        );

        return !!response.data.access_token;
    } catch (error) {
        return false;
    }
}

async function testSuperAdminAccess(
    keycloakUrl: string,
    instance: string,
    username: string,
    password: string
): Promise<{ hasToken: boolean; hasSuperAdminRole: boolean }> {
    try {
        const tokenUrl = `${keycloakUrl}/realms/${REALM}/protocol/openid-connect/token`;
        
        const response = await axios.post(
            tokenUrl,
            new URLSearchParams({
                grant_type: 'password',
                client_id: 'dive-v3-client',
                username,
                password
            }),
            { headers: { 'Content-Type': 'application/x-www-form-urlencoded' } }
        );

        const token = response.data.access_token;
        if (!token) {
            return { hasToken: false, hasSuperAdminRole: false };
        }

        // Decode JWT to check roles (simple base64 decode)
        const parts = token.split('.');
        if (parts.length !== 3) {
            return { hasToken: true, hasSuperAdminRole: false };
        }

        const payload = JSON.parse(Buffer.from(parts[1], 'base64').toString());
        const roles = payload.realm_access?.roles || payload.roles || [];
        const hasSuperAdmin = roles.includes('super_admin');

        return { hasToken: true, hasSuperAdminRole: hasSuperAdmin };
    } catch (error) {
        return { hasToken: false, hasSuperAdminRole: false };
    }
}

// ============================================
// MAIN EXECUTION
// ============================================

async function setupInstance(instance: string): Promise<void> {
    console.log(`\n${'='.repeat(60)}`);
    console.log(`Setting up instance: ${instance}`);
    console.log('='.repeat(60));

    const config = INSTANCE_CONFIG[instance];
    if (!config) {
        console.error(`  ERROR: No configuration found for instance ${instance}`);
        return;
    }

    const keycloakUrl = config.url;
    console.log(`  Keycloak URL: ${keycloakUrl}`);

    try {
        // Authenticate
        const adminToken = await getAdminToken(keycloakUrl, instance);
        const client = createKcAdminClient(keycloakUrl, instance);
        await authenticateKcClient(client, instance);

        console.log(`  ✅ Authenticated\n`);

        // Create demo users (levels 1-4)
        console.log('Creating demo users...');
        for (const level of ['1', '2', '3', '4']) {
            await createDemoUser(client, instance, level, adminToken, keycloakUrl);
        }

        // Create super admin user
        console.log('\nCreating super admin user...');
        await createSuperAdminUser(client, instance, adminToken, keycloakUrl);

        console.log(`\n✅ Instance ${instance} setup complete!`);

    } catch (error: any) {
        console.error(`\n❌ ERROR setting up instance ${instance}:`, error.message);
        if (error.response?.data) {
            console.error('  Response:', JSON.stringify(error.response.data, null, 2));
        }
    }
}

async function printCredentialsList(): Promise<void> {
    console.log(`\n${'='.repeat(60)}`);
    console.log('DEMO CREDENTIALS - READY FOR PRESENTATION');
    console.log('='.repeat(60));
    console.log('\n📋 DEMO USERS (4 per instance):');
    console.log('   Format: demo-{instance}-{level}');
    console.log('   Password: Demo2025!Secure');
    console.log('   OTP Code: 123456 (for demo purposes)\n');

    for (const instance of INSTANCES) {
        console.log(`\n${instance}:`);
        for (const level of ['1', '2', '3', '4']) {
            const config = CLEARANCE_LEVELS[level as keyof typeof CLEARANCE_LEVELS];
            const username = `demo-${instance.toLowerCase()}-${level}`;
            console.log(`  ${username.padEnd(20)} | ${config.clearance.padEnd(12)} | ${DEMO_PASSWORD}`);
        }
    }

    console.log(`\n\n🔐 SUPER ADMIN USERS:`);
    console.log('   Format: admin-{instance}');
    console.log('   Password: Admin2025!Secure');
    console.log('   OTP Code: 123456 (for demo purposes)\n');

    for (const instance of INSTANCES) {
        const username = `admin-${instance.toLowerCase()}`;
        console.log(`  ${username.padEnd(20)} | ${SUPER_ADMIN_PASSWORD}`);
    }

    console.log(`\n\n📝 NOTES:`);
    console.log('  • OTP codes are pre-configured with secret: DEMO123456789012345678901234567890');
    console.log('  • For demo purposes, use code: 123456');
    console.log('  • Super admin users have super_admin role for /admin/dashboard access');
    console.log('  • UNCLASSIFIED users (level 1) do not require MFA');
    console.log('  • TOP_SECRET users (level 4) require WebAuthn (passkey)');
    console.log('  • SECRET/CONFIDENTIAL users (levels 2-3) require OTP');
    console.log('\n');
}

async function main() {
    console.log('\n╔════════════════════════════════════════════════════════════════╗');
    console.log('║     DIVE V3 - Demo Users Setup for Presentation                ║');
    console.log('╚════════════════════════════════════════════════════════════════╝\n');

    // Setup all instances
    for (const instance of INSTANCES) {
        await setupInstance(instance);
    }

    // Print credentials list
    await printCredentialsList();

    console.log('✅ Setup complete! Users are ready for demo.\n');
}

// Run if executed directly
if (require.main === module) {
    main().catch((error) => {
        console.error('\n❌ FATAL ERROR:', error);
        process.exit(1);
    });
}

export { setupInstance, printCredentialsList, INSTANCES, INSTANCE_CONFIG, REALM, DEMO_PASSWORD, SUPER_ADMIN_PASSWORD };

