# =============================================================================
# Policy Rollout Module - Main Resources
# =============================================================================
# This module manages canary deployments for OPA policies in DIVE V3.
#
# Deployment Strategies:
#   - canary: Gradual traffic shifting (0% → 10% → 25% → 50% → 100%)
#   - blue-green: Instant slot switch with rollback capability
#   - rolling: Gradual instance-by-instance update
#
# Usage:
#   module "policy_rollout" {
#     source            = "../modules/policy-rollout"
#     environment       = "prod"
#     tenant_code       = "USA"
#     policy_version    = "v1.2.3"
#     canary_percentage = 10
#   }
#
# References:
#   - DIVE V3 Policy Spec: docs/PHASE-3-IMPLEMENTATION-PROMPT.md
# =============================================================================

# -----------------------------------------------------------------------------
# Local Values
# -----------------------------------------------------------------------------

locals {
  # Unique deployment identifier
  deployment_id = "${var.tenant_code}-${var.environment}-${var.policy_version}-${formatdate("YYYYMMDD-hhmmss", timestamp())}"

  # Common labels
  common_labels = merge({
    "dive.environment"    = var.environment
    "dive.tenant"         = var.tenant_code
    "dive.component"      = "policy-rollout"
    "dive.policy-version" = var.policy_version
    "dive.deployment-id"  = local.deployment_id
    "dive.managed-by"     = "terraform"
  }, var.labels)

  # Canary stages for progressive rollout
  canary_stages = [0, 10, 25, 50, 75, 100]
  current_stage = var.canary_percentage
  next_stage    = min([for s in local.canary_stages : s if s > var.canary_percentage]...)

  # Deployment state file path
  state_file_path = "${path.root}/.policy-rollout-state/${var.tenant_code}-${var.environment}.json"
}

# -----------------------------------------------------------------------------
# Deployment State Directory
# -----------------------------------------------------------------------------

resource "local_file" "state_directory" {
  filename = "${path.root}/.policy-rollout-state/.gitkeep"
  content  = "# Policy rollout state files - do not commit to git\n"
}

# -----------------------------------------------------------------------------
# Deployment State File
# -----------------------------------------------------------------------------
# Tracks the current deployment state for rollback and audit.

resource "local_file" "deployment_state" {
  filename = local.state_file_path
  content = jsonencode({
    deployment_id       = local.deployment_id
    tenant_code         = var.tenant_code
    environment         = var.environment
    policy_version      = var.policy_version
    deployment_strategy = var.deployment_strategy
    active_slot         = var.active_slot
    canary_percentage   = var.canary_percentage
    created_at          = timestamp()
    status              = "active"
  })
}

# -----------------------------------------------------------------------------
# Pre-Deployment Validation Script
# -----------------------------------------------------------------------------

resource "local_file" "pre_deploy_script" {
  filename = "${path.root}/scripts/policy-rollout-validate.sh"
  content  = <<-EOF
#!/bin/bash
# =============================================================================
# Policy Pre-Deployment Validation Script
# Generated by Terraform for ${var.tenant_code} ${var.environment}
# Deployment ID: ${local.deployment_id}
# =============================================================================

set -e

POLICY_PATH="${var.policy_bundle_path}"
OPA_BIN="${var.opa_binary_path}"
MIN_COVERAGE=${var.minimum_test_coverage}
BASELINE_PATH="${var.baseline_path}"

echo "========================================"
echo "Pre-Deployment Validation"
echo "Policy Version: ${var.policy_version}"
echo "Environment: ${var.environment}"
echo "Tenant: ${var.tenant_code}"
echo "========================================"

# Step 1: Rego Syntax Validation
echo ""
echo "Step 1/4: Syntax Validation..."
if $OPA_BIN check "$POLICY_PATH" --strict; then
    echo "✓ Syntax validation passed"
else
    echo "✗ Syntax validation failed"
    exit 1
fi

# Step 2: Run Policy Tests
echo ""
echo "Step 2/4: Running Policy Tests..."
%{if var.require_tests_pass}
TEST_OUTPUT=$($OPA_BIN test "$POLICY_PATH" -v 2>&1)
TEST_RESULT=$?

if [ $TEST_RESULT -eq 0 ]; then
    PASS_COUNT=$(echo "$TEST_OUTPUT" | grep -c "PASS:" || echo "0")
    echo "✓ All tests passed ($PASS_COUNT tests)"
else
    echo "✗ Tests failed"
    echo "$TEST_OUTPUT" | tail -20
    exit 1
fi
%{else}
echo "⚠ Test requirement disabled - skipping"
%{endif}

# Step 3: Coverage Check
echo ""
echo "Step 3/4: Coverage Check (minimum: $MIN_COVERAGE%)..."
COVERAGE_OUTPUT=$($OPA_BIN test "$POLICY_PATH" --coverage --format=json 2>/dev/null || echo '{"coverage":0}')
COVERAGE=$(echo "$COVERAGE_OUTPUT" | grep -o '"coverage":[0-9.]*' | cut -d: -f2 | cut -d. -f1)

if [ -z "$COVERAGE" ]; then
    COVERAGE=0
fi

if [ "$COVERAGE" -ge "$MIN_COVERAGE" ]; then
    echo "✓ Coverage: $COVERAGE% (minimum: $MIN_COVERAGE%)"
else
    echo "✗ Coverage too low: $COVERAGE% (minimum: $MIN_COVERAGE%)"
    exit 1
fi

# Step 4: Baseline Comparison
echo ""
echo "Step 4/4: Baseline Comparison..."
%{if var.enable_baseline_comparison}
if [ -d "$BASELINE_PATH" ] && [ -f "$BASELINE_PATH/latest.json" ]; then
    echo "Comparing against baseline: $BASELINE_PATH/latest.json"
    # Note: Full baseline comparison requires the capture-baseline.ts script
    echo "⚠ Baseline comparison requires manual verification"
else
    echo "⚠ No baseline found - skipping comparison"
fi
%{else}
echo "⚠ Baseline comparison disabled - skipping"
%{endif}

echo ""
echo "========================================"
echo "✓ Pre-deployment validation PASSED"
echo "========================================"
echo ""
echo "Ready to deploy. Next steps:"
echo "  - Review validation results above"
echo "  - Run: ./scripts/policy-rollout-deploy.sh"
EOF

  file_permission = "0755"
}

# -----------------------------------------------------------------------------
# Deployment Script
# -----------------------------------------------------------------------------

resource "local_file" "deploy_script" {
  filename = "${path.root}/scripts/policy-rollout-deploy.sh"
  content  = <<-EOF
#!/bin/bash
# =============================================================================
# Policy Deployment Script
# Generated by Terraform for ${var.tenant_code} ${var.environment}
# Deployment ID: ${local.deployment_id}
# =============================================================================

set -e

DEPLOYMENT_ID="${local.deployment_id}"
TENANT="${var.tenant_code}"
ENVIRONMENT="${var.environment}"
POLICY_VERSION="${var.policy_version}"
CANARY_PERCENTAGE=${var.canary_percentage}
ACTIVE_SLOT="${var.active_slot}"
STRATEGY="${var.deployment_strategy}"

echo "========================================"
echo "Policy Deployment"
echo "Deployment ID: $DEPLOYMENT_ID"
echo "Strategy: $STRATEGY"
echo "Active Slot: $ACTIVE_SLOT"
echo "Canary Percentage: $CANARY_PERCENTAGE%"
echo "========================================"

# Notify deployment start
%{if var.notification_webhook != ""}
curl -s -X POST "${var.notification_webhook}" \
  -H "Content-Type: application/json" \
  -d '{"event":"deploy_start","deployment_id":"'"$DEPLOYMENT_ID"'","tenant":"'"$TENANT"'","version":"'"$POLICY_VERSION"'"}'
%{endif}

case "$STRATEGY" in
  "canary")
    echo ""
    echo "Deploying with canary strategy ($CANARY_PERCENTAGE% traffic)..."
    
    if [ "$CANARY_PERCENTAGE" -eq 0 ]; then
        echo "Canary at 0% - preparing canary slot..."
        echo "Use 'terraform apply -var=canary_percentage=10' to start canary rollout"
    elif [ "$CANARY_PERCENTAGE" -eq 100 ]; then
        echo "Canary at 100% - promotion complete!"
        echo "Consider switching active slot with 'terraform apply -var=active_slot=green'"
    else
        echo "Canary active at $CANARY_PERCENTAGE%"
        echo "Use 'terraform apply -var=canary_percentage=${min(var.canary_percentage + var.canary_increment, 100)}' to promote"
    fi
    ;;
    
  "blue-green")
    echo ""
    echo "Deploying with blue-green strategy..."
    echo "Current active slot: $ACTIVE_SLOT"
    echo "New deployment will go to: $([ "$ACTIVE_SLOT" = "blue" ] && echo "green" || echo "blue")"
    echo ""
    echo "After verification, switch with: terraform apply -var=active_slot=$([ "$ACTIVE_SLOT" = "blue" ] && echo "green" || echo "blue")"
    ;;
    
  "rolling")
    echo ""
    echo "Deploying with rolling strategy..."
    echo "Instances will be updated one at a time"
    ;;
esac

echo ""
echo "========================================"
echo "✓ Deployment initiated"
echo "========================================"
echo ""
echo "Next steps:"
echo "  1. Monitor health: ./scripts/policy-rollout-health.sh"
echo "  2. Promote canary: ./scripts/policy-rollout-promote.sh"
echo "  3. If issues: ./scripts/policy-rollout-rollback.sh"
EOF

  file_permission = "0755"
}

# -----------------------------------------------------------------------------
# Canary Promotion Script
# -----------------------------------------------------------------------------

resource "local_file" "promote_script" {
  filename = "${path.root}/scripts/policy-rollout-promote.sh"
  content  = <<-EOF
#!/bin/bash
# =============================================================================
# Canary Promotion Script
# Generated by Terraform for ${var.tenant_code} ${var.environment}
# =============================================================================

set -e

CURRENT_PERCENTAGE=${var.canary_percentage}
INCREMENT=${var.canary_increment}
NEXT_PERCENTAGE=$((CURRENT_PERCENTAGE + INCREMENT))

if [ "$NEXT_PERCENTAGE" -gt 100 ]; then
    NEXT_PERCENTAGE=100
fi

echo "========================================"
echo "Canary Promotion"
echo "Current: $CURRENT_PERCENTAGE%"
echo "Next: $NEXT_PERCENTAGE%"
echo "========================================"

if [ "$CURRENT_PERCENTAGE" -eq 100 ]; then
    echo "Canary already at 100% - deployment complete!"
    echo ""
    echo "Consider finalizing by switching active slot:"
    echo "  terraform apply -var='active_slot=${var.active_slot == "blue" ? "green" : "blue"}'"
    exit 0
fi

echo ""
echo "Running health check before promotion..."
./scripts/policy-rollout-health.sh

if [ $? -ne 0 ]; then
    echo ""
    echo "✗ Health check failed - aborting promotion"
    echo "Run './scripts/policy-rollout-rollback.sh' if needed"
    exit 1
fi

echo ""
echo "To promote canary from $CURRENT_PERCENTAGE% to $NEXT_PERCENTAGE%, run:"
echo "  terraform apply -var='canary_percentage=$NEXT_PERCENTAGE'"
echo ""
echo "For full promotion (100%), run:"
echo "  terraform apply -var='canary_percentage=100'"
EOF

  file_permission = "0755"
}

# -----------------------------------------------------------------------------
# Rollback Script
# -----------------------------------------------------------------------------

resource "local_file" "rollback_script" {
  filename = "${path.root}/scripts/policy-rollout-rollback.sh"
  content  = <<-EOF
#!/bin/bash
# =============================================================================
# Policy Rollback Script
# Generated by Terraform for ${var.tenant_code} ${var.environment}
# =============================================================================

set -e

echo "========================================"
echo "Policy Rollback"
echo "Environment: ${var.environment}"
echo "Tenant: ${var.tenant_code}"
echo "========================================"

# Notify rollback
%{if var.notification_webhook != ""}
curl -s -X POST "${var.notification_webhook}" \
  -H "Content-Type: application/json" \
  -d '{"event":"rollback","deployment_id":"${local.deployment_id}","tenant":"${var.tenant_code}"}'
%{endif}

case "${var.deployment_strategy}" in
  "canary")
    echo ""
    echo "Rolling back canary deployment..."
    echo "Setting canary percentage to 0%"
    echo ""
    echo "Run: terraform apply -var='canary_percentage=0'"
    ;;
    
  "blue-green")
    echo ""
    echo "Rolling back to previous slot..."
    echo "Current: ${var.active_slot}"
    echo "Reverting to: ${var.active_slot == "blue" ? "green" : "blue"}"
    echo ""
    echo "Run: terraform apply -var='active_slot=${var.active_slot == "blue" ? "green" : "blue"}'"
    ;;
    
  "rolling")
    echo ""
    echo "Rolling back instances..."
    echo "This may take several minutes"
    ;;
esac

echo ""
echo "After rollback, verify health with:"
echo "  ./scripts/policy-rollout-health.sh"
EOF

  file_permission = "0755"
}

# -----------------------------------------------------------------------------
# Health Check Script
# -----------------------------------------------------------------------------

resource "local_file" "health_check_script" {
  filename = "${path.root}/scripts/policy-rollout-health.sh"
  content  = <<-EOF
#!/bin/bash
# =============================================================================
# Policy Health Check Script
# Generated by Terraform for ${var.tenant_code} ${var.environment}
# =============================================================================

set -e

OPA_PORT=8181
DEPLOYMENT_ID="${local.deployment_id}"

echo "========================================"
echo "Policy Health Check"
echo "Deployment: $DEPLOYMENT_ID"
echo "========================================"

# Check OPA is responding
echo -n "OPA API: "
if curl -sf "http://localhost:$OPA_PORT/health" > /dev/null; then
    echo "✓ Healthy"
else
    echo "✗ Not responding"
    exit 1
fi

# Check policy evaluation
echo -n "Policy Eval: "
TEST_INPUT='{"input":{"subject":{"authenticated":true,"uniqueID":"healthcheck","clearance":"SECRET","countryOfAffiliation":"USA"},"action":"read","resource":{"classification":"UNCLASSIFIED","releasabilityTo":["USA"]}}}'

RESULT=$(curl -sf -X POST "http://localhost:$OPA_PORT/v1/data/dive/authz/decision" \
  -H "Content-Type: application/json" \
  -d "$TEST_INPUT" 2>/dev/null || echo '{}')

if echo "$RESULT" | grep -q '"allow"'; then
    DECISION=$(echo "$RESULT" | grep -o '"allow":[^,}]*' | cut -d: -f2)
    echo "✓ Working (allow=$DECISION)"
else
    echo "✗ Policy evaluation failed"
    echo "Response: $RESULT"
    exit 1
fi

# Check decision latency
echo -n "Latency: "
START=$(date +%s%N)
curl -sf -X POST "http://localhost:$OPA_PORT/v1/data/dive/authz/decision" \
  -H "Content-Type: application/json" \
  -d "$TEST_INPUT" > /dev/null 2>&1
END=$(date +%s%N)
LATENCY_MS=$(((END - START) / 1000000))

if [ "$LATENCY_MS" -lt ${var.rollback_on_latency_p95} ]; then
    echo "✓ $${LATENCY_MS}ms (threshold: ${var.rollback_on_latency_p95}ms)"
else
    echo "⚠ $${LATENCY_MS}ms (above threshold: ${var.rollback_on_latency_p95}ms)"
fi

echo ""
echo "========================================"
echo "✓ Health check PASSED"
echo "========================================"
EOF

  file_permission = "0755"
}

# -----------------------------------------------------------------------------
# Time-Based Resources for Deployment Tracking
# -----------------------------------------------------------------------------

resource "time_static" "deployment_timestamp" {
  triggers = {
    deployment_id = local.deployment_id
  }
}

# -----------------------------------------------------------------------------
# Validation: Pre-deployment checks
# -----------------------------------------------------------------------------

resource "null_resource" "pre_deploy_validation" {
  count = var.require_tests_pass ? 1 : 0

  triggers = {
    policy_version = var.policy_version
    deployment_id  = local.deployment_id
  }

  provisioner "local-exec" {
    command     = "echo 'Validating policy bundle before deployment...'"
    working_dir = path.root
  }
}

# -----------------------------------------------------------------------------
# Gitignore for State Files
# -----------------------------------------------------------------------------

resource "local_file" "gitignore" {
  filename = "${path.root}/.policy-rollout-state/.gitignore"
  content  = <<-EOF
# Policy rollout state files - generated by Terraform
# These files track deployment state and should not be committed
*.json
!.gitkeep
EOF
}






