version: 2
updates:
  # Backend npm dependencies
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "dive-v3-team"
    labels:
      - "dependencies"
      - "backend"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    # Ignore major version updates (require manual review)
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    # Group minor and patch updates together
    groups:
      production-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  
  # Frontend npm dependencies
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "dive-v3-team"
    labels:
      - "dependencies"
      - "frontend"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      production-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  
  # KAS npm dependencies
  - package-ecosystem: "npm"
    directory: "/kas"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "dive-v3-team"
    labels:
      - "dependencies"
      - "kas"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
  
  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
    open-pull-requests-limit: 5
    reviewers:
      - "dive-v3-team"
    labels:
      - "dependencies"
      - "docker"
      - "infrastructure"
    commit-message:
      prefix: "chore(docker)"
    # Docker images to monitor
    # Backend Dockerfile
    # Frontend Dockerfile
    # docker-compose.yml base images
  
  # Backend Dockerfile
  - package-ecosystem: "docker"
    directory: "/backend"
    schedule:
      interval: "weekly"
    reviewers:
      - "dive-v3-team"
    labels:
      - "dependencies"
      - "docker"
      - "backend"
  
  # Frontend Dockerfile
  - package-ecosystem: "docker"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    reviewers:
      - "dive-v3-team"
    labels:
      - "dependencies"
      - "docker"
      - "frontend"
  
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "11:00"
    open-pull-requests-limit: 5
    reviewers:
      - "dive-v3-team"
    labels:
      - "dependencies"
      - "github-actions"
      - "ci-cd"
    commit-message:
      prefix: "chore(ci)"

