#!/bin/bash
#
# Generate Test RSA Keys for E2E JWT Testing
# 
# Creates RSA key pair for signing/verifying test JWT tokens
# - Private key: Used to sign test JWTs (RS256)
# - Public key: Used to verify test JWTs (mocked in JWKS endpoint)
#
# These keys are ONLY for testing and should NOT be used in production
#

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
KEYS_DIR="$SCRIPT_DIR/../src/__tests__/keys"

echo "🔐 Generating Test RSA Keys for E2E Testing"
echo "============================================"
echo ""

# Create keys directory
mkdir -p "$KEYS_DIR"

# Generate private key (2048-bit RSA)
echo "📝 Generating private key (2048-bit RSA)..."
openssl genrsa -out "$KEYS_DIR/test-private-key.pem" 2048 2>/dev/null

# Generate public key from private key
echo "📝 Generating public key..."
openssl rsa -in "$KEYS_DIR/test-private-key.pem" -pubout -out "$KEYS_DIR/test-public-key.pem" 2>/dev/null

# Set appropriate permissions
chmod 600 "$KEYS_DIR/test-private-key.pem"
chmod 644 "$KEYS_DIR/test-public-key.pem"

echo ""
echo "✅ Test RSA keys generated successfully!"
echo ""
echo "📂 Key Locations:"
echo "   Private: $KEYS_DIR/test-private-key.pem"
echo "   Public:  $KEYS_DIR/test-public-key.pem"
echo ""
echo "🔒 Private key permissions: 600 (read/write owner only)"
echo "📖 Public key permissions:  644 (readable by all)"
echo ""
echo "⚠️  IMPORTANT:"
echo "   - These keys are for TESTING ONLY"
echo "   - DO NOT use in production"
echo "   - Keys are committed to repo for consistent test behavior"
echo "   - Private key is safe to commit (test-only, no real data)"
echo ""

# Create README for keys directory
cat > "$KEYS_DIR/README.md" << 'EOF'
# Test RSA Keys

**Purpose:** RSA key pair for E2E test JWT signing/verification

## Files

- `test-private-key.pem` - Private key for signing test JWTs (RS256)
- `test-public-key.pem` - Public key for verifying test JWTs
- `README.md` - This file

## Usage

### Signing Test JWTs

```typescript
import fs from 'fs';
import jwt from 'jsonwebtoken';

const privateKey = fs.readFileSync(
  path.join(__dirname, 'keys/test-private-key.pem'),
  'utf8'
);

const token = jwt.sign({ sub: 'test' }, privateKey, { algorithm: 'RS256' });
```

### Verifying Test JWTs

```typescript
const publicKey = fs.readFileSync(
  path.join(__dirname, 'keys/test-public-key.pem'),
  'utf8'
);

const decoded = jwt.verify(token, publicKey, { algorithms: ['RS256'] });
```

### Mocking JWKS Endpoint

```typescript
import { importSPKI, exportJWK } from 'jose';

const publicKey = await importSPKI(publicKeyPem, 'RS256');
const jwk = await exportJWK(publicKey);

nock(keycloakUrl)
  .get('/realms/test/protocol/openid-connect/certs')
  .reply(200, { keys: [{ ...jwk, kid: 'test-key-1' }] });
```

## Security Notes

⚠️ **TESTING ONLY** - These keys are for test environments only:

- ✅ Safe to commit to repository
- ✅ Used only in test environment
- ✅ No real user data or production use
- ❌ DO NOT use in production
- ❌ DO NOT use for real authentication

## Key Properties

- **Algorithm:** RSA
- **Key Size:** 2048 bits
- **Format:** PEM
- **Type:** PKCS#8 (private), SPKI (public)

## Generated By

Script: `backend/scripts/generate-test-rsa-keys.sh`  
Date: Auto-generated during test setup  
Purpose: E2E test JWT authentication (RS256)

## References

- Investigation: `E2E-TEST-INVESTIGATION.md`
- Implementation: Option D (Mock JWKS Endpoint)
- Tests: `backend/src/__tests__/e2e/*.test.ts`
EOF

echo "📄 Created README.md in keys directory"
echo ""
echo "✅ Setup complete! Test RSA keys ready for E2E testing."
