/**
 * RS256 JWT Utilities for E2E Testing
 * 
 * Creates JWT tokens signed with RSA private key (RS256 algorithm)
 * to match production Keycloak token format.
 * 
 * Use with mock-jwks.ts to mock Keycloak JWKS endpoint.
 */

import jwt from 'jsonwebtoken';
import fs from 'fs';
import path from 'path';
import { IJWTPayload } from './mock-jwt';

/**
 * Load test RSA private key (generated by generate-test-rsa-keys.sh)
 */
const PRIVATE_KEY_PATH = path.join(__dirname, '../keys/test-private-key.pem');

let privateKey: string;
try {
    privateKey = fs.readFileSync(PRIVATE_KEY_PATH, 'utf8');
} catch (error) {
    throw new Error(
        `Failed to load test RSA private key from ${PRIVATE_KEY_PATH}. ` +
        `Run: npm run generate-test-keys`
    );
}

/**
 * Test key ID (must match JWKS mock)
 */
export const TEST_KEY_ID = 'test-key-1';

/**
 * Default Keycloak issuer for tests
 */
const DEFAULT_ISSUER = process.env.KEYCLOAK_URL
    ? `${process.env.KEYCLOAK_URL}/realms/${process.env.KEYCLOAK_REALM || 'dive-v3-broker-usa'}`
    : 'http://localhost:8081/realms/dive-v3-broker-usa';

/**
 * Create an RS256 JWT token for E2E testing
 * 
 * Matches production Keycloak token format:
 * - RS256 algorithm (RSA asymmetric)
 * - Signed with test private key
 * - Includes kid header (key ID)
 * - Standard Keycloak claims
 * 
 * @param claims Custom claims to include in the token
 * @returns Signed JWT token string (RS256)
 */
export function createE2EJWT(claims: Partial<IJWTPayload> = {}): string {
    const now = Math.floor(Date.now() / 1000);

    const defaultClaims: IJWTPayload = {
        sub: 'testuser-us',
        uniqueID: 'testuser-us',
        email: 'testuser@example.mil',
        preferred_username: 'testuser-us',
        clearance: 'SECRET',
        countryOfAffiliation: 'USA',
        acpCOI: ['FVEY'],
        iss: DEFAULT_ISSUER,
        aud: 'dive-v3-client',
        exp: now + 3600, // Expires in 1 hour
        iat: now,
        // AAL2/FAL2 defaults
        acr: 'urn:mace:incommon:iap:silver',
        amr: ['pwd', 'otp'],
        auth_time: now
    };

    const payload = { ...defaultClaims, ...claims };

    return jwt.sign(payload, privateKey, {
        algorithm: 'RS256',
        header: {
            kid: TEST_KEY_ID,  // Key ID (must match JWKS mock)
            typ: 'JWT',
            alg: 'RS256'
        }
    });
}

/**
 * Create an RS256 JWT for a U.S. user with SECRET clearance
 */
export function createUSUserE2EJWT(overrides: Partial<IJWTPayload> = {}): string {
    return createE2EJWT({
        sub: 'testuser-us',
        uniqueID: 'testuser-us',
        email: 'testuser@example.mil',
        clearance: 'SECRET',
        countryOfAffiliation: 'USA',
        acpCOI: ['FVEY'],
        ...overrides
    });
}

/**
 * Create an RS256 JWT for a French user with CONFIDENTIAL clearance
 */
export function createFrenchUserE2EJWT(overrides: Partial<IJWTPayload> = {}): string {
    return createE2EJWT({
        sub: 'testuser-fra',
        uniqueID: 'testuser-fra',
        email: 'testuser@gouv.fr',
        clearance: 'CONFIDENTIAL',
        countryOfAffiliation: 'FRA',
        acpCOI: ['NATO-COSMIC'],
        ...overrides
    });
}

/**
 * Create an RS256 JWT for a Canadian user with TOP_SECRET clearance
 */
export function createCanadianUserE2EJWT(overrides: Partial<IJWTPayload> = {}): string {
    return createE2EJWT({
        sub: 'testuser-can',
        uniqueID: 'testuser-can',
        email: 'testuser@gc.ca',
        clearance: 'TOP_SECRET',
        countryOfAffiliation: 'CAN',
        acpCOI: ['FVEY'],
        ...overrides
    });
}

/**
 * Create an RS256 JWT for an industry contractor with UNCLASSIFIED clearance
 */
export function createContractorE2EJWT(overrides: Partial<IJWTPayload> = {}): string {
    return createE2EJWT({
        sub: 'bob.contractor',
        uniqueID: 'bob.contractor',
        email: 'bob@contractor.com',
        clearance: 'UNCLASSIFIED',
        countryOfAffiliation: 'USA',
        acpCOI: [],
        ...overrides
    });
}

/**
 * Create an expired RS256 JWT token
 */
export function createExpiredE2EJWT(claims: Partial<IJWTPayload> = {}): string {
    const now = Math.floor(Date.now() / 1000);
    return createE2EJWT({
        ...claims,
        exp: now - 3600, // Expired 1 hour ago
        iat: now - 7200
    });
}

/**
 * Get the test public key (for manual verification if needed)
 */
export function getTestPublicKey(): string {
    const publicKeyPath = path.join(__dirname, '../keys/test-public-key.pem');
    return fs.readFileSync(publicKeyPath, 'utf8');
}
