# =============================================================================
# Vault Production Config — Node 1
# =============================================================================
# Hardened configuration for production environments (DIVE_ENV=production).
# Differences from staging: UI disabled, stricter TTLs, WARN log level,
# unauthenticated metrics disabled, mlock enabled, TLS enabled.
# TLS certs generated by: ./dive vault tls-setup (uses mkcert).
# =============================================================================

storage "raft" {
  path    = "/vault/data"
  node_id = "vault-1"

  retry_join {
    leader_api_addr    = "https://vault-2:8200"
    leader_ca_cert_file = "/vault/certs/ca.pem"
  }
  retry_join {
    leader_api_addr    = "https://vault-3:8200"
    leader_ca_cert_file = "/vault/certs/ca.pem"
  }
}

seal "transit" {
  address         = "http://vault-seal:8200"
  token           = "env://VAULT_TRANSIT_SEAL_TOKEN"
  disable_renewal = "false"
  key_name        = "autounseal"
  mount_path      = "transit/"
  tls_skip_verify = "true"
}

listener "tcp" {
  address       = "0.0.0.0:8200"
  tls_disable   = 0
  tls_cert_file = "/vault/certs/certificate.pem"
  tls_key_file  = "/vault/certs/key.pem"

  telemetry {
    unauthenticated_metrics_access = false
  }
}

telemetry {
  prometheus_retention_time = "30s"
  disable_hostname         = true
}

api_addr      = "https://vault-1:8200"
cluster_addr  = "https://vault-1:8201"
ui            = false
log_level     = "WARN"
disable_mlock = false

max_lease_ttl     = "768h"
default_lease_ttl = "168h"
