# DIVE V3 - External Spain SAML IdP Configuration
# Deploys Spain SAML (SimpleSAMLphp) to Keycloak broker realm

module "spain_saml_idp" {
  source = "./modules/external-idp-saml"

  # Basic Configuration
  realm_id         = "dive-v3-broker"
  idp_alias        = "esp-realm-external"
  idp_display_name = "Spain Ministry of Defense (External SAML)"
  country_code     = "ESP"

  # SAML Configuration - SimpleSAMLphp v2.4.3
  # Use localhost:9443 (external access) - Docker network accessible
  # SimpleSAMLphp auto-generates SSO/SLO endpoints from baseurlpath
  idp_entity_id = "http://localhost:9443/simplesaml/saml2/idp/metadata.php"
  idp_sso_url   = "http://localhost:9443/simplesaml/module.php/saml/idp/singleSignOnService"
  idp_slo_url   = "http://localhost:9443/simplesaml/module.php/saml/idp/singleLogout"

  # Certificate (placeholder - will be updated from generated cert)
  # This certificate is generated by external-idps/scripts/generate-spain-saml-certs.sh
  # For production, replace with actual CA-signed certificate
  idp_certificate = file("${path.module}/../external-idps/spain-saml/cert/server.crt")

  # SAML Settings
  name_id_policy_format     = "Transient" # keycloak/keycloak v5.x format (was: urn:oasis:names:tc:SAML:2.0:nameid-format:transient)
  signature_algorithm       = "RSA_SHA256"
  want_assertions_signed    = true
  want_assertions_encrypted = false
  force_authn               = false

  # IdP Behavior
  enabled     = true
  trust_email = true
  store_token = false
  link_only   = false

  # Authentication Flows
  first_broker_login_flow_alias = "first broker login"
  post_broker_login_flow_alias  = ""

  # Spanish Military Attribute Mappings
  # Maps Spanish defense attributes to DIVE standard claims
  # SimpleSAMLphp v2.4.3 already normalizes attributes in saml20-idp-hosted.php
  attribute_mappings = {
    clearance = {
      saml_attribute_name        = "nivelSeguridad"
      saml_attribute_name_format = "urn:oasis:names:tc:SAML:2.0:attrname-format:basic"
      user_attribute_name        = "clearanceOriginal"
      sync_mode                  = "INHERIT"
    }
    coi = {
      saml_attribute_name        = "acpCOI"
      saml_attribute_name_format = "urn:oasis:names:tc:SAML:2.0:attrname-format:basic"
      user_attribute_name        = "acpCOI"
      sync_mode                  = "INHERIT"
    }
    countryOfAffiliation = {
      saml_attribute_name        = "paisAfiliacion"
      saml_attribute_name_format = "urn:oasis:names:tc:SAML:2.0:attrname-format:basic"
      user_attribute_name        = "countryOfAffiliationOriginal"
      sync_mode                  = "INHERIT"
    }
    organization = {
      saml_attribute_name        = "organizacion"
      saml_attribute_name_format = "urn:oasis:names:tc:SAML:2.0:attrname-format:basic"
      user_attribute_name        = "dutyOrg"
      sync_mode                  = "INHERIT"
    }
    displayName = {
      saml_attribute_name        = "displayName"
      saml_attribute_name_format = "urn:oasis:names:tc:SAML:2.0:attrname-format:basic"
      user_attribute_name        = "displayName"
      sync_mode                  = "INHERIT"
    }
  }
}

# Output for verification
output "spain_saml_idp_alias" {
  description = "Spain SAML IdP alias"
  value       = module.spain_saml_idp.idp_alias
}

output "spain_saml_idp_redirect_uri" {
  description = "Redirect URI for Spain SAML IdP configuration"
  value       = module.spain_saml_idp.idp_redirect_uri
}

output "spain_saml_attribute_mappers" {
  description = "Created attribute mappers"
  value       = module.spain_saml_idp.attribute_mappers
}

