#!/bin/bash
# =============================================================================
# DIVE V3 - Terraform .tfvars Generator
# =============================================================================
# Purpose: Auto-generate Terraform variable files from federation-registry.json
# Usage: ./scripts/federation/generate-tfvars.sh [instance_code]
#        If no instance specified, generates for all instances
# =============================================================================

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
REGISTRY_FILE="$PROJECT_ROOT/config/federation-registry.json"
OUTPUT_DIR="$PROJECT_ROOT/terraform/instances"

# Logging functions
log_info() {
    echo -e "${BLUE}ℹ${NC} $1"
}

log_success() {
    echo -e "${GREEN}✓${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}⚠${NC} $1"
}

log_error() {
    echo -e "${RED}✗${NC} $1"
}

# Validate registry first
validate_registry() {
    log_info "Validating federation registry..."
    
    if [ ! -f "$REGISTRY_FILE" ]; then
        log_error "Registry file not found: $REGISTRY_FILE"
        exit 1
    fi
    
    if ! jq empty "$REGISTRY_FILE" 2>/dev/null; then
        log_error "Invalid JSON in registry file"
        exit 1
    fi
    
    log_success "Registry validated"
}

# Generate .tfvars for a single instance
generate_tfvars() {
    local instance_code="$1"
    local instance_code_lower=$(echo "$instance_code" | tr '[:upper:]' '[:lower:]')
    
    log_info "Generating .tfvars for $instance_code..."
    
    # Check if instance exists
    if ! jq -e ".instances.$instance_code_lower" "$REGISTRY_FILE" > /dev/null 2>&1; then
        log_error "Instance '$instance_code' not found in registry"
        return 1
    fi
    
    # Extract instance data
    local instance_name=$(jq -r ".instances.$instance_code_lower.name" "$REGISTRY_FILE")
    local instance_type=$(jq -r ".instances.$instance_code_lower.type" "$REGISTRY_FILE")
    local app_url=$(jq -r ".instances.$instance_code_lower.urls.app" "$REGISTRY_FILE")
    local api_url=$(jq -r ".instances.$instance_code_lower.urls.api" "$REGISTRY_FILE")
    local idp_url=$(jq -r ".instances.$instance_code_lower.urls.idp" "$REGISTRY_FILE")
    local keycloak_port=$(jq -r ".instances.$instance_code_lower.ports.keycloak" "$REGISTRY_FILE")
    local admin_username=$(jq -r ".instances.$instance_code_lower.keycloak.adminUsername" "$REGISTRY_FILE")
    local admin_password=$(jq -r ".defaults.adminPassword" "$REGISTRY_FILE")
    local create_test_users=$(jq -r ".instances.$instance_code_lower.testUsers.create" "$REGISTRY_FILE")
    
    # Determine keycloak_url based on instance type
    local keycloak_url
    if [ "$instance_type" = "local" ]; then
        keycloak_url="https://localhost:$keycloak_port"
    else
        # Remote instance - use public URL
        keycloak_url="$idp_url"
    fi
    
    # Create output file
    local output_file="$OUTPUT_DIR/${instance_code_lower}.tfvars"
    
    cat > "$output_file" <<EOF
# ${instance_name} Instance Configuration
# =============================================================================
# ⚠️  AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
# =============================================================================
# This file is automatically generated from config/federation-registry.json
# To make changes:
#   1. Edit config/federation-registry.json
#   2. Run: ./scripts/federation/generate-tfvars.sh
#   3. Commit the registry change (this file is regenerated)
#
# Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Source: federation-registry.json v$(jq -r '.version' "$REGISTRY_FILE")
# =============================================================================

keycloak_url            = "$keycloak_url"
keycloak_admin_username = "$admin_username"
keycloak_admin_password = "$admin_password"
app_url                 = "$app_url"
api_url                 = "$api_url"
idp_url                 = "$idp_url"
create_test_users       = $create_test_users

# Federation partners - URLs must match actual deployment URLs
federation_partners = {
EOF
    
    # Generate federation partner entries
    local partners=$(jq -r ".federation.matrix.$instance_code_lower[]?" "$REGISTRY_FILE")
    
    for partner in $partners; do
        local partner_code=$(echo "$partner" | tr '[:lower:]' '[:upper:]')
        local partner_name=$(jq -r ".instances.$partner.name" "$REGISTRY_FILE")
        local partner_idp_url=$(jq -r ".instances.$partner.urls.idp" "$REGISTRY_FILE")
        local partner_enabled=$(jq -r ".instances.$partner.enabled" "$REGISTRY_FILE")
        
        cat >> "$output_file" <<EOF
  $partner = {
    instance_code = "$partner_code"
    instance_name = "$partner_name"
    idp_url       = "$partner_idp_url"
    enabled       = $partner_enabled
  }
EOF
    done
    
    # Close the federation_partners block
    echo "}" >> "$output_file"
    
    log_success "Generated: $output_file"
    return 0
}

# Main execution
main() {
    echo ""
    echo "═══════════════════════════════════════════════════════════"
    echo "  DIVE V3 Terraform .tfvars Generator"
    echo "═══════════════════════════════════════════════════════════"
    echo ""
    
    # Validate registry
    validate_registry
    
    # Create output directory if it doesn't exist
    mkdir -p "$OUTPUT_DIR"
    
    # Determine which instances to generate
    if [ $# -eq 0 ]; then
        # No arguments - generate for all instances
        log_info "Generating .tfvars for all instances..."
        local instances=$(jq -r '.instances | keys[]' "$REGISTRY_FILE")
        
        for instance in $instances; do
            generate_tfvars "$instance" || true
        done
    else
        # Generate for specified instance
        local instance_code=$(echo "$1" | tr '[:upper:]' '[:lower:]')
        generate_tfvars "$instance_code"
    fi
    
    echo ""
    log_success "Terraform .tfvars generation complete!"
    echo ""
    echo "Next steps:"
    echo "  1. Review generated files in $OUTPUT_DIR"
    echo "  2. Run: cd terraform/instances && terraform workspace select <instance>"
    echo "  3. Run: terraform plan -var-file=<instance>.tfvars"
    echo ""
}

# Run main function
main "$@"
