#!/usr/local/bin/bash
# =============================================================================
# DIVE V3 CLI - Help Module
# =============================================================================
# Provides comprehensive help for all CLI commands and federation features
# Documentation: docs/HUB_SPOKE_ARCHITECTURE.md, docs/HUB_SPOKE_101_DEPLOYMENT.md
# =============================================================================

# Ensure common functions are loaded
if [ -z "$DIVE_COMMON_LOADED" ]; then
    source "$(dirname "${BASH_SOURCE[0]}")/common.sh"
    export DIVE_COMMON_LOADED=1
fi

cmd_help() {
    print_header
    echo "Usage: ./dive [options] [command] [subcommand] [args...]"
    echo ""
    echo -e "${BOLD}Global Options:${NC}"
    echo "  --env <env>         Set environment: local, gcp, pilot (default: local)"
    echo "  --instance <inst>   Set instance: usa, fra, deu, gbr, nzl (default: usa)"
    echo "  --dry-run           Show what would be done without executing"
    echo "  --verbose           Show detailed output"
    echo "  --quiet             Suppress non-essential output"
    echo ""
    echo -e "${BOLD}Core Commands:${NC}"
    echo "  up                  Start the stack"
    echo "  down                Stop the stack"
    echo "  restart [service]   Restart stack or specific service"
    echo "  logs [service]      View logs (follow mode)"
    echo "  ps                  List running containers"
    echo "  exec <svc> [cmd]    Execute command in container"
    echo "  status              Show overall status"
    echo "  health              Health check all services"
    echo ""
    echo -e "${BOLD}Deployment Commands:${NC}"
    echo "  deploy              Full deployment workflow"
    echo "  validate            Validate prerequisites and configuration"
    echo "  reset               Reset to clean state (nuke + deploy)"
    echo "  nuke                Destroy everything (containers + volumes)"
    echo ""
    echo -e "${BOLD}Database Commands:${NC}"
    echo "  seed [instance]     Seed database with test data"
    echo "  backup              Create database backup"
    echo "  restore <dir>       Restore from backup"
    echo ""
    echo -e "${BOLD}Terraform Commands:${NC}"
    echo "  tf plan             Show Terraform plan"
    echo "  tf apply            Apply Terraform configuration"
    echo "  tf destroy          Destroy Terraform resources"
    echo "  tf output           Show Terraform outputs"
    echo ""
    echo -e "${BOLD}Secrets Commands:${NC}"
    echo "  secrets list        List all DIVE secrets in GCP"
    echo "  secrets show        Show secrets for current instance"
    echo "  secrets load        Load secrets into environment"
    echo "  secrets verify      Verify secrets can be accessed"
    echo "  secrets export      Export secrets as shell commands"
    echo ""
    echo -e "${BOLD}Remote Pilot Commands:${NC}"
    echo "  pilot up            Start services on pilot VM"
    echo "  pilot down          Stop services on pilot VM"
    echo "  pilot status        Show pilot VM status"
    echo "  pilot logs [svc]    View pilot VM logs"
    echo "  pilot ssh           SSH into pilot VM"
    echo "  pilot reset         Reset pilot VM to clean state"
    echo "  pilot deploy        Full deployment to pilot VM"
    echo ""
    echo -e "${BOLD}SP Client Registration (Pilot Mode):${NC}"
    echo "  sp register             Register as SP Client (OAuth/OIDC)"
    echo "  sp status [sp-id]       Show SP registration status"
    echo "  sp list                 List all registered SP Clients"
    echo "  sp credentials [sp-id]  Show SP credentials"
    echo ""
    echo -e "${BOLD}Hub-Spoke Federation:${NC}"
    if [ "$PILOT_MODE" = true ]; then
        echo -e "  ${GRAY}(Some spoke commands disabled in pilot mode)${NC}"
    fi
    echo ""
    echo -e "  ${CYAN}Hub Commands (Central Authority):${NC}"
    echo "    hub start             Start hub services (OPAL Server, Registry)"
    echo "    hub status            Show hub service status"
    echo "    hub instances         List all registered spokes"
    echo "    hub push-policy       Push policy update to all spokes"
    echo ""
    echo -e "  ${CYAN}Spoke Commands (Partner Instances):${NC}"
    echo "    spoke init <code> <name>   Initialize new spoke instance"
    echo "    spoke generate-certs       Generate X.509 certificates for mTLS"
    echo "    spoke rotate-certs         Rotate certificates (with backup)"
    echo "    spoke register             Register spoke with hub"
    echo "    spoke status               Show spoke federation status"
    echo "    spoke health               Check all spoke service health"
    echo "    spoke up                   Start spoke services"
    echo "    spoke down                 Stop spoke services"
    echo "    spoke logs [service]       View spoke service logs"
    echo "    spoke sync                 Force policy sync from hub"
    echo "    spoke heartbeat            Send manual heartbeat to hub"
    echo ""
    echo -e "  ${CYAN}Spoke Resilience (Failover/Offline):${NC}"
    echo "    spoke failover status      Show circuit breaker state"
    echo "    spoke failover force-open  Force offline mode (stop hub sync)"
    echo "    spoke failover force-closed Force normal mode (resume sync)"
    echo "    spoke failover reset       Reset circuit breaker metrics"
    echo "    spoke maintenance enter    Enter maintenance mode"
    echo "    spoke maintenance exit     Exit maintenance mode"
    echo "    spoke audit-status         Show audit queue status"
    echo ""
    echo -e "  ${CYAN}Federation Status:${NC}"
    echo "    federation status          Show overall federation status"
    echo "    federation link <CODE>     Link IdP for cross-border SSO"
    echo "    federation unlink <CODE>   Remove IdP link"
    echo "    federation list-idps       List configured identity providers"
    echo "    federation sync-policies   Pull latest policies from hub"
    echo "    federation sync-idps       Sync IdP metadata from hub"
    echo "    federation push-audit      Push queued audit logs to hub"
    echo ""
    echo -e "  ${GREEN}${BOLD}${CYAN}Federation Mappers (NATO Nations):${NC}"
    echo "    federation mappers list           List all 32 NATO nation templates"
    echo "    federation mappers show <nation>  Show mapper configuration"
    echo "    federation mappers apply <nation> Apply mappers to instance"
    echo "    federation mappers verify <nation> Verify mapper setup"
    echo ""
    echo -e "${BOLD}Policy Commands (OPAL):${NC}"
    echo "  policy build [--sign]       Build OPA policy bundle"
    echo "  policy push                 Push bundle to OPAL Server"
    echo "  policy status               Show policy distribution status"
    echo "  policy test [pattern]       Run OPA policy tests"
    echo "  policy version              Show current policy version"
    echo "  policy refresh              Trigger OPAL policy refresh"
    echo ""
    echo -e "${BOLD}Other Commands:${NC}"
    echo "  info                Show environment info"
    echo "  help                Show this help"
    echo ""
    echo -e "${BOLD}Quick Start Examples:${NC}"
    echo ""
    echo "  # Start the hub (USA instance)"
    echo "  ./dive up"
    echo ""
    echo "  # Deploy a new spoke (e.g., New Zealand)"
    echo "  ./dive spoke init NZL 'New Zealand Defence Force'"
    echo "  ./dive --instance nzl spoke generate-certs"
    echo "  ./dive --instance nzl spoke register"
    echo "  # ... wait for hub admin approval ..."
    echo "  ./dive --instance nzl spoke up"
    echo ""
    echo "  # Check federation status"
    echo "  ./dive federation status"
    echo "  ./dive --instance nzl spoke health"
    echo ""
    echo "  # Push policy update from hub to all spokes"
    echo "  ./dive policy build --sign"
    echo "  ./dive hub push-policy"
    echo ""
    echo -e "${BOLD}Pilot Mode:${NC}"
    if [ "$PILOT_MODE" = true ]; then
        echo -e "  Status: ${GREEN}Enabled${NC} (spoke deployment commands restricted)"
        echo "  Partners should use: ./dive sp register (OAuth/OIDC mode)"
    else
        echo -e "  Status: ${YELLOW}Disabled${NC} (full spoke deployment available)"
    fi
    echo ""
    echo "  To toggle pilot mode:"
    echo "    export DIVE_PILOT_MODE=true   # Enable pilot mode"
    echo "    export DIVE_PILOT_MODE=false  # Disable pilot mode"
    echo ""
    echo -e "${BOLD}Documentation:${NC}"
    echo "  Hub-Spoke Architecture:    docs/HUB_SPOKE_ARCHITECTURE.md"
    echo "  101 Deployment Guide:      docs/HUB_SPOKE_101_DEPLOYMENT.md"
    echo "  Partner Onboarding:        docs/PARTNER-ONBOARDING-GUIDE.md"
    echo "  Distributed Architecture:  docs/DISTRIBUTED-ARCHITECTURE.md"
    echo ""
}

module_help() {
    cmd_help
}



