name: 'E2E Test Setup'
description: 'Shared setup for DIVE V3 E2E test jobs: Node.js, deps, SSL, Keycloak, PostgreSQL, backend HTTPS, Playwright, Next.js HTTPS, optional OPA'

inputs:
  nextauth-secret:
    description: 'NEXTAUTH_SECRET for the Next.js server'
    required: true
  keycloak-users:
    description: 'JSON array of Keycloak user configs. Each: {"username":"...","password":"...","clearance":"...","coi":[...]}'
    required: false
    default: '[{"username":"admin-dive","password":"Admin123!","clearance":"TOP_SECRET","coi":[]},{"username":"testuser-unclass","password":"Unclass123!","clearance":"UNCLASSIFIED","coi":[]}]'
  start-opa:
    description: 'Whether to start OPA server (true/false)'
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: Setup Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: |
          frontend/package-lock.json
          backend/package-lock.json

    - name: Install Frontend Dependencies
      shell: bash
      run: cd frontend && npm ci --legacy-peer-deps

    - name: Install Backend Dependencies
      shell: bash
      run: cd backend && npm ci --legacy-peer-deps

    - name: Generate SSL Certificates
      shell: bash
      run: |
        mkdir -p ${{ github.workspace }}/frontend/certs \
                 ${{ github.workspace }}/keycloak-certs \
                 ${{ github.workspace }}/certs

        # Frontend certificates
        openssl req -x509 -newkey rsa:4096 -nodes \
          -keyout ${{ github.workspace }}/frontend/certs/key.pem \
          -out ${{ github.workspace }}/frontend/certs/certificate.pem \
          -days 1 -subj "/C=US/ST=Test/L=Test/O=DIVE V3/CN=localhost"

        # Keycloak certificates
        openssl req -x509 -newkey rsa:4096 -nodes \
          -keyout ${{ github.workspace }}/keycloak-certs/key.pem \
          -out ${{ github.workspace }}/keycloak-certs/cert.pem \
          -days 1 -subj "/C=US/ST=Test/L=Test/O=DIVE V3 CI/CN=localhost" \
          -addext "subjectAltName=DNS:localhost,DNS:keycloak,IP:127.0.0.1"
        chmod 644 ${{ github.workspace }}/keycloak-certs/cert.pem \
                  ${{ github.workspace }}/keycloak-certs/key.pem

        # OPA certificates (always generated for simplicity)
        openssl req -x509 -newkey rsa:4096 -nodes \
          -keyout ${{ github.workspace }}/certs/key.pem \
          -out ${{ github.workspace }}/certs/certificate.pem \
          -days 1 -subj "/C=US/ST=Test/L=Test/O=DIVE V3 CI/CN=localhost" \
          -addext "subjectAltName=DNS:localhost,DNS:opa,IP:127.0.0.1"

        # Build a CA bundle for Node-based services that must trust multiple
        # self-signed certs in CI (frontend/backend HTTPS + Keycloak HTTPS).
        cat ${{ github.workspace }}/frontend/certs/certificate.pem \
            ${{ github.workspace }}/keycloak-certs/cert.pem \
            > ${{ github.workspace }}/certs/ca-bundle.pem

        echo "::notice::SSL certificates generated"

    - name: Start Keycloak
      shell: bash
      run: |
        docker run -d --name keycloak \
          -p 8443:8443 \
          -p 9000:9000 \
          -e KC_BOOTSTRAP_ADMIN_USERNAME=admin \
          -e KC_BOOTSTRAP_ADMIN_PASSWORD=admin \
          -e KC_HTTPS_CERTIFICATE_FILE=/opt/keycloak/certs/cert.pem \
          -e KC_HTTPS_CERTIFICATE_KEY_FILE=/opt/keycloak/certs/key.pem \
          -e KC_HEALTH_ENABLED=true \
          -e KC_HOSTNAME_STRICT=false \
          -v ${{ github.workspace }}/keycloak-certs:/opt/keycloak/certs:ro \
          quay.io/keycloak/keycloak:26.4.2 start-dev

        max_attempts=300
        for i in $(seq 1 "$max_attempts"); do
          # Keycloak health endpoints are served on management port 9000.
          if curl -kfsS https://localhost:9000/health/ready >/dev/null 2>&1; then
            echo "::notice::Keycloak management health ready"
            break
          fi

          # Fallback: confirm the public OIDC endpoint is reachable.
          if curl -kfsS https://localhost:8443/realms/master/.well-known/openid-configuration >/dev/null 2>&1; then
            echo "::notice::Keycloak OIDC endpoint ready"
            break
          fi

          if ! docker ps --filter "name=^/keycloak$" --filter "status=running" --format '{{.Names}}' | grep -q '^keycloak$'; then
            echo "::error::Keycloak container exited before becoming ready"
            docker logs --tail 300 keycloak || true
            exit 1
          fi

          if [ "$i" -eq "$max_attempts" ]; then
            echo "::error::Keycloak failed to become ready after 10 minutes"
            docker logs --tail 300 keycloak
            exit 1
          fi
          sleep 2
        done

    - name: Configure Keycloak Realm and Users
      shell: bash
      run: |
        TOKEN=""
        for i in {1..30}; do
          TOKEN=$(curl -sk -X POST https://localhost:8443/realms/master/protocol/openid-connect/token \
            -d "client_id=admin-cli&username=admin&password=admin&grant_type=password" | jq -r '.access_token // empty')
          if [ -n "$TOKEN" ]; then
            break
          fi
          sleep 2
        done

        if [ -z "$TOKEN" ]; then
          echo "::error::Failed to obtain Keycloak admin token"
          docker logs --tail 300 keycloak
          exit 1
        fi

        REALM="dive-v3-broker-usa"

        # Create realm
        curl -sk -X POST https://localhost:8443/admin/realms \
          -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/json" \
          -d "{\"realm\":\"$REALM\",\"enabled\":true}" || true

        # Create OIDC client for NextAuth
        curl -sk -X POST "https://localhost:8443/admin/realms/$REALM/clients" \
          -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/json" \
          -d '{
            "clientId": "dive-v3-broker-usa",
            "enabled": true,
            "protocol": "openid-connect",
            "publicClient": false,
            "secret": "test-client-secret",
            "redirectUris": ["https://localhost:3000/*"],
            "webOrigins": ["https://localhost:3000"],
            "directAccessGrantsEnabled": true,
            "standardFlowEnabled": true
          }' || true
        echo "::notice::OIDC client created in $REALM"

        # Create users from JSON input
        echo '${{ inputs.keycloak-users }}' | jq -c '.[]' | while read -r user; do
          username=$(echo "$user" | jq -r '.username')
          password=$(echo "$user" | jq -r '.password')
          clearance=$(echo "$user" | jq -r '.clearance')
          coi=$(echo "$user" | jq -c '.coi // []')

          curl -sk -X POST "https://localhost:8443/admin/realms/$REALM/users" \
            -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/json" \
            -d "{\"username\":\"$username\",\"enabled\":true,\"credentials\":[{\"type\":\"password\",\"value\":\"$password\",\"temporary\":false}],\"attributes\":{\"clearance\":[\"$clearance\"],\"countryOfAffiliation\":[\"USA\"],\"acpCOI\":$coi}}" || true

          echo "::notice::Created user: $username ($clearance)"
        done

        # Ensure baseline AAL1 test user exists for Playwright auth state generation.
        curl -sk -X POST "https://localhost:8443/admin/realms/$REALM/users" \
          -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/json" \
          -d "{\"username\":\"testuser-usa-1\",\"enabled\":true,\"credentials\":[{\"type\":\"password\",\"value\":\"TestUser2025!Pilot\",\"temporary\":false}],\"attributes\":{\"clearance\":[\"UNCLASSIFIED\"],\"countryOfAffiliation\":[\"USA\"],\"acpCOI\":[]}}" || true
        echo "::notice::Ensured baseline user: testuser-usa-1"

    - name: Setup PostgreSQL Schema
      shell: bash
      run: cd frontend && npx drizzle-kit push --force || true
      env:
        DATABASE_URL: postgresql://postgres:password@localhost:5432/dive_v3_app

    - name: Cache Playwright Browsers
      uses: actions/cache@v4
      id: playwright-cache
      with:
        path: ~/.cache/ms-playwright
        key: playwright-${{ runner.os }}-${{ hashFiles('frontend/package-lock.json') }}

    - name: Install Playwright Browsers
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      shell: bash
      run: cd frontend && npx playwright install chromium --with-deps

    - name: Install Playwright System Dependencies
      if: steps.playwright-cache.outputs.cache-hit == 'true'
      shell: bash
      run: cd frontend && npx playwright install-deps chromium

    - name: Start Backend HTTPS Server
      shell: bash
      run: |
        cd backend
        nohup npx tsx src/https-server.ts > backend.log 2>&1 &
        BACKEND_PID=$!
        echo "Backend PID: $BACKEND_PID"

        for i in {1..90}; do
          if curl -kfsS https://localhost:4000/api/health/live >/dev/null 2>&1; then
            echo "::notice::Backend HTTPS server ready"
            break
          fi

          if ! kill -0 "$BACKEND_PID" 2>/dev/null; then
            echo "::error::Backend process exited before becoming ready"
            tail -n 300 backend.log || true
            exit 1
          fi

          if [ $i -eq 90 ]; then
            echo "::error::Backend failed to become ready on https://localhost:4000"
            tail -n 300 backend.log || true
            exit 1
          fi
          sleep 2
        done
      env:
        NODE_ENV: test
        PORT: "4000"
        SSL_CERT_PATH: ${{ github.workspace }}/frontend/certs
        MONGODB_URL: mongodb://localhost:27017/dive-v3-test
        MONGODB_DATABASE: dive-v3-test
        DATABASE_URL: postgresql://postgres:password@localhost:5432/dive_v3_app
        KEYCLOAK_URL: https://localhost:8443
        KEYCLOAK_REALM: dive-v3-broker-usa
        NEXT_PUBLIC_KEYCLOAK_URL: https://localhost:8443
        NEXT_PUBLIC_KEYCLOAK_REALM: dive-v3-broker-usa
        KEYCLOAK_CLIENT_ID: dive-v3-broker-usa
        KEYCLOAK_CLIENT_SECRET: test-client-secret
        KEYCLOAK_INSECURE_SKIP_VERIFY: "true"
        KEYCLOAK_ADMIN_USER: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
        KC_ADMIN_PASSWORD: admin
        ALLOW_INSECURE_LOCAL_DEVELOPMENT: "true"

    - name: Start Next.js HTTPS Server
      shell: bash
      run: |
        cd frontend
        nohup node -e "
          const { createServer } = require('https');
          const { parse } = require('url');
          const next = require('next');
          const fs = require('fs');
          const app = next({ dev: true });
          const handle = app.getRequestHandler();
          app.prepare().then(() => {
            createServer({
              key: fs.readFileSync('certs/key.pem'),
              cert: fs.readFileSync('certs/certificate.pem')
            }, (req, res) => handle(req, res, parse(req.url, true)))
            .listen(3000, () => console.log('Ready on https://localhost:3000'));
          });
        " > nextjs.log 2>&1 &

        for i in {1..60}; do
          if curl -k -f https://localhost:3000 2>/dev/null; then
            echo "::notice::Next.js HTTPS server ready"
            break
          fi
          if [ $i -eq 60 ]; then
            echo "::error::Next.js failed to start"
            cat nextjs.log
            exit 1
          fi
          sleep 2
        done
      env:
        NODE_ENV: development
        NEXTAUTH_URL: https://localhost:3000
        NEXTAUTH_SECRET: ${{ inputs.nextauth-secret }}
        DATABASE_URL: postgresql://postgres:password@localhost:5432/dive_v3_app
        KEYCLOAK_URL: https://localhost:8443
        KEYCLOAK_REALM: dive-v3-broker-usa
        NEXT_PUBLIC_KEYCLOAK_URL: https://localhost:8443
        NEXT_PUBLIC_KEYCLOAK_REALM: dive-v3-broker-usa
        KEYCLOAK_CLIENT_ID: dive-v3-broker-usa
        KEYCLOAK_CLIENT_SECRET: test-client-secret
        KEYCLOAK_INSECURE_SKIP_VERIFY: "true"
        BACKEND_URL: https://localhost:4000
        NEXT_PUBLIC_API_URL: https://localhost:4000
        NODE_EXTRA_CA_CERTS: ${{ github.workspace }}/certs/ca-bundle.pem
        MONGODB_URL: mongodb://localhost:27017/dive-v3-test

    - name: Generate Playwright Auth State Files
      shell: bash
      run: |
        cd frontend
        npx tsx -e "import setup from './src/__tests__/e2e/fixtures/auth-setup.ts'; (async () => { await setup({ projects: [{ use: { baseURL: process.env.BASE_URL || 'https://localhost:3000' } }] } as any); })().catch((error) => { console.error(error); process.exit(1); });"

        if [ ! -f .auth/aal1.json ]; then
          echo "::error::Missing required Playwright auth state: .auth/aal1.json"
          exit 1
        fi

        if [ ! -f .auth/admin.json ]; then
          echo "::warning::Admin auth state was not generated (.auth/admin.json)"
        fi
      env:
        BASE_URL: https://localhost:3000
        CI: "true"
        ENABLE_MFA_TESTS: "false"

    - name: Start OPA Server
      if: inputs.start-opa == 'true'
      shell: bash
      run: |
        curl -L -o opa https://openpolicyagent.org/downloads/latest/opa_linux_amd64_static
        chmod +x opa
        nohup ./opa run --server --addr=:8181 --log-level=error \
          --tls-cert-file=${{ github.workspace }}/certs/certificate.pem \
          --tls-private-key-file=${{ github.workspace }}/certs/key.pem \
          > opa.log 2>&1 &
        sleep 5
        curl -k -f https://localhost:8181/health || (cat opa.log && exit 1)
        echo "::notice::OPA server ready"
