#!/bin/bash

###############################################################################################
# Deploy FRA Instance Alongside USA Instance
# 
# Refactored to use unified multi-instance architecture with consistent usa-*/fra-* naming.
#
# This script:
#   1. Ensures USA instance is running with usa-* Cloudflare hostnames
#   2. Extracts Keycloak client secrets from Terraform state
#   3. Sets up FRA Cloudflare tunnel with fra-* hostnames
#   4. Deploys FRA services on different ports
#   5. Syncs Keycloak realm from USA to FRA
#
# Naming Convention: ISO 3166-1 alpha-3 prefix (usa-*, fra-*, deu-*, etc.)
#
# USA Ports: 3000, 4000, 8443, 8080, 27017, 5433, 6379, 8181
# FRA Ports: 3001, 4001, 8444, 8083, 27018, 5434, 6380, 8182
#
# Usage: ./scripts/deploy-fra-alongside-usa.sh [--skip-tunnel] [--skip-sync]
###############################################################################################

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
MAGENTA='\033[0;35m'
NC='\033[0m'

# Script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

# Configuration
SKIP_TUNNEL=false
SKIP_SYNC=false

# Parse arguments
for arg in "$@"; do
  case $arg in
    --skip-tunnel) SKIP_TUNNEL=true ;;
    --skip-sync) SKIP_SYNC=true ;;
  esac
done

# Hostnames (consistent ISO 3166-1 alpha-3 naming)
USA_APP="usa-app.dive25.com"
USA_API="usa-api.dive25.com"
USA_IDP="usa-idp.dive25.com"
FRA_APP="fra-app.dive25.com"
FRA_API="fra-api.dive25.com"
FRA_IDP="fra-idp.dive25.com"
FRA_KAS="fra-kas.dive25.com"

cd "$PROJECT_ROOT"

clear
echo -e "${MAGENTA}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${MAGENTA}     DIVE V3 - Deploy FRA Instance Alongside USA${NC}"
echo -e "${MAGENTA}═══════════════════════════════════════════════════════════════${NC}"
echo ""

# ============================================================================
# Step 0: Generate SSL certificates
# ============================================================================
echo -e "${CYAN}[0/8] Generating SSL certificates for all hostnames...${NC}"
if [ -f "$SCRIPT_DIR/generate-dev-certs.sh" ]; then
  "$SCRIPT_DIR/generate-dev-certs.sh" > /dev/null 2>&1 && \
    echo -e "${GREEN}✓ SSL certificates generated${NC}" || \
    echo -e "${YELLOW}⚠ Certificate generation had warnings${NC}"
else
  echo -e "${YELLOW}⚠ Certificate generator not found, using existing certs${NC}"
fi

# ============================================================================
# Step 1: Verify USA instance
# ============================================================================
echo ""
echo -e "${CYAN}[1/8] Verifying USA instance...${NC}"

USA_RUNNING=false
if docker ps | grep -q "dive-v3-frontend"; then
  USA_RUNNING=true
  echo -e "${GREEN}✓ USA Docker containers running${NC}"
else
  echo -e "${YELLOW}! USA instance not running - starting it...${NC}"
  docker-compose up -d
  sleep 20
fi

# Ensure USA tunnel is running
if ! ps aux | grep -q "[c]loudflared.*dive-v3-tunnel"; then
  echo "  Starting USA Cloudflare tunnel..."
  nohup cloudflared tunnel --config ~/.cloudflared/config.yml run dive-v3-tunnel > /tmp/dive-v3-tunnel.log 2>&1 &
  sleep 3
fi
echo -e "${GREEN}✓ USA tunnel running${NC}"

# Quick health check
USA_HEALTH=$(curl -sk https://localhost:3000 -o /dev/null -w '%{http_code}' --max-time 3 || echo "000")
echo -e "${GREEN}✓ USA Frontend: ${USA_HEALTH}${NC}"

# ============================================================================
# Step 2: Extract secrets from Terraform
# ============================================================================
echo ""
echo -e "${CYAN}[2/8] Extracting Keycloak client secrets from Terraform...${NC}"

cd "$PROJECT_ROOT/terraform"
FRA_CLIENT_SECRET=$(terraform output -raw fra_client_secret 2>/dev/null || echo "")

if [ -z "$FRA_CLIENT_SECRET" ] || [ "$FRA_CLIENT_SECRET" = "null" ]; then
  echo -e "${YELLOW}⚠ FRA client secret not found in Terraform, generating placeholder${NC}"
  FRA_CLIENT_SECRET="fra-placeholder-secret-will-be-replaced"
fi

cd "$PROJECT_ROOT"
echo -e "${GREEN}✓ Client secrets ready${NC}"

# ============================================================================
# Step 3: Update docker-compose and generate .env files
# ============================================================================
echo ""
echo -e "${CYAN}[3/8] Generating environment configuration...${NC}"

# Update docker-compose.fra.yml with correct secrets
sed -i.bak "s/KEYCLOAK_CLIENT_SECRET:.*/KEYCLOAK_CLIENT_SECRET: ${FRA_CLIENT_SECRET}/" docker-compose.fra.yml 2>/dev/null || true

# Generate frontend .env.fra file
cat > frontend/.env.fra << EOF
# FRA Instance Environment Variables
# Auto-generated by deploy-fra-alongside-usa.sh
# Naming: ISO 3166-1 alpha-3 prefix (usa-*, fra-*)

# Client-side variables (accessible in browser)
NEXT_PUBLIC_API_URL=https://${FRA_API}
NEXT_PUBLIC_BACKEND_URL=https://${FRA_API}
NEXT_PUBLIC_KEYCLOAK_URL=https://${FRA_IDP}
NEXT_PUBLIC_KEYCLOAK_REALM=dive-v3-broker
NEXT_PUBLIC_KEYCLOAK_CLIENT_ID=dive-v3-client-broker
NEXT_PUBLIC_APP_NAME=DIVE V3 - France Instance
NEXT_PUBLIC_INSTANCE=FRA

# Server-side variables (secrets - not accessible in browser)
KEYCLOAK_CLIENT_ID=dive-v3-client-broker
KEYCLOAK_CLIENT_SECRET=${FRA_CLIENT_SECRET}
KEYCLOAK_REALM=dive-v3-broker
KEYCLOAK_URL=https://keycloak-fra:8443
NEXTAUTH_URL=https://${FRA_APP}
NEXTAUTH_SECRET=fra-frontend-secret-change-in-production
EOF

echo -e "${GREEN}✓ Environment files generated${NC}"

# ============================================================================
# Step 4: Setup Docker network
# ============================================================================
echo ""
echo -e "${CYAN}[4/8] Setting up Docker network...${NC}"
docker network create fra-network --subnet=172.22.0.0/16 2>/dev/null && \
  echo -e "${GREEN}✓ Created fra-network${NC}" || \
  echo -e "${YELLOW}✓ Network already exists${NC}"

# ============================================================================
# Step 5: Setup Cloudflare tunnel
# ============================================================================
echo ""
if [ "$SKIP_TUNNEL" = false ]; then
  echo -e "${CYAN}[5/8] Setting up FRA Cloudflare tunnel...${NC}"
  
  TUNNEL_NAME="dive-v3-fra"
  TUNNEL_CONFIG="$HOME/.cloudflared/dive-v3-fra-config.yml"
  
  # Check if tunnel exists
  if cloudflared tunnel list 2>/dev/null | grep -q "$TUNNEL_NAME"; then
    TUNNEL_ID=$(cloudflared tunnel list | grep "$TUNNEL_NAME" | awk '{print $1}')
    echo -e "${YELLOW}✓ Tunnel exists: ${TUNNEL_ID}${NC}"
  else
    echo "  Creating tunnel..."
    TUNNEL_OUTPUT=$(cloudflared tunnel create "$TUNNEL_NAME" 2>&1)
    TUNNEL_ID=$(echo "$TUNNEL_OUTPUT" | grep -oE '[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}' | head -1)
    echo -e "${GREEN}✓ Created tunnel: ${TUNNEL_ID}${NC}"
  fi
  
  # Add DNS routes
  if [ -n "$TUNNEL_ID" ]; then
    echo "  Adding DNS routes..."
    cloudflared tunnel route dns "$TUNNEL_NAME" "$FRA_APP" 2>/dev/null || true
    cloudflared tunnel route dns "$TUNNEL_NAME" "$FRA_API" 2>/dev/null || true
    cloudflared tunnel route dns "$TUNNEL_NAME" "$FRA_IDP" 2>/dev/null || true
    cloudflared tunnel route dns "$TUNNEL_NAME" "$FRA_KAS" 2>/dev/null || true
    
    # Create tunnel config
    mkdir -p "$HOME/.cloudflared"
    cat > "$TUNNEL_CONFIG" << EOF
tunnel: ${TUNNEL_ID}
credentials-file: ${HOME}/.cloudflared/${TUNNEL_ID}.json

ingress:
  # FRA Frontend
  - hostname: ${FRA_APP}
    service: https://localhost:3001
    originRequest:
      noTLSVerify: true
      connectTimeout: 30s

  # FRA Backend API
  - hostname: ${FRA_API}
    service: https://localhost:4001
    originRequest:
      noTLSVerify: true
      connectTimeout: 30s

  # FRA Keycloak IdP
  - hostname: ${FRA_IDP}
    service: https://localhost:8444
    originRequest:
      noTLSVerify: true
      connectTimeout: 30s

  # FRA KAS
  - hostname: ${FRA_KAS}
    service: http://localhost:8083
    originRequest:
      connectTimeout: 30s

  # Catch-all
  - service: http_status:404
EOF
    echo -e "${GREEN}✓ Tunnel configuration created${NC}"
  fi
  
  # Start tunnel
  pkill -f "dive-v3-fra" 2>/dev/null || true
  sleep 2
  nohup cloudflared tunnel --config "$TUNNEL_CONFIG" run "$TUNNEL_NAME" > /tmp/fra-tunnel.log 2>&1 &
  sleep 3
  echo -e "${GREEN}✓ FRA tunnel started${NC}"
else
  echo -e "${YELLOW}[5/8] Skipping Cloudflare tunnel (--skip-tunnel)${NC}"
fi

# ============================================================================
# Step 6: Start FRA database services
# ============================================================================
echo ""
echo -e "${CYAN}[6/8] Starting FRA database services...${NC}"
docker-compose -p fra -f docker-compose.fra.yml up -d postgres-fra mongodb-fra redis-fra
echo "  Waiting for databases..."
sleep 10
echo -e "${GREEN}✓ Database services started${NC}"

# ============================================================================
# Step 7: Start FRA core services (Keycloak, OPA)
# ============================================================================
echo ""
echo -e "${CYAN}[7/8] Starting FRA core services...${NC}"
docker-compose -p fra -f docker-compose.fra.yml up -d keycloak-fra opa-fra
echo "  Waiting for Keycloak..."
sleep 20
echo -e "${GREEN}✓ Core services started${NC}"

# ============================================================================
# Step 8: Sync Keycloak and start application services
# ============================================================================
echo ""
echo -e "${CYAN}[8/8] Syncing Keycloak and starting applications...${NC}"

if [ "$SKIP_SYNC" = false ]; then
  # Wait for FRA Keycloak to be ready
  for i in {1..30}; do
    if curl -sk https://localhost:8444/realms/master > /dev/null 2>&1; then
      break
    fi
    sleep 2
  done
  
  # Run the sync script
  if [ -f "$SCRIPT_DIR/sync-keycloak-realm.sh" ]; then
    "$SCRIPT_DIR/sync-keycloak-realm.sh" usa fra
  else
    echo -e "${YELLOW}⚠ Sync script not found, manual sync required${NC}"
  fi
else
  echo -e "${YELLOW}⚠ Skipping Keycloak sync (--skip-sync)${NC}"
fi

# Start application services
docker-compose -p fra -f docker-compose.fra.yml up -d kas-fra backend-fra frontend-fra
echo -e "${GREEN}✓ Application services started${NC}"

# ============================================================================
# Final Summary
# ============================================================================
echo ""
echo -e "${GREEN}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}     ✅ Both Instances Deployed!${NC}"
echo -e "${GREEN}═══════════════════════════════════════════════════════════════${NC}"
echo ""

echo -e "${CYAN}Instance Summary:${NC}"
echo ""
printf "%-12s %-30s %-30s\n" "Service" "🇺🇸 USA" "🇫🇷 FRA"
printf "%-12s %-30s %-30s\n" "-------" "---" "---"
printf "%-12s %-30s %-30s\n" "App" "https://${USA_APP}" "https://${FRA_APP}"
printf "%-12s %-30s %-30s\n" "API" "https://${USA_API}" "https://${FRA_API}"
printf "%-12s %-30s %-30s\n" "IdP" "https://${USA_IDP}" "https://${FRA_IDP}"
printf "%-12s %-30s %-30s\n" "Local App" "localhost:3000" "localhost:3001"
printf "%-12s %-30s %-30s\n" "Local KC" "localhost:8443" "localhost:8444"
echo ""

echo -e "${CYAN}Quick Commands:${NC}"
echo "  Check status:  ./scripts/manage-instances.sh status"
echo "  Re-sync FRA:   ./scripts/manage-instances.sh sync fra"
echo "  Stop FRA:      ./scripts/manage-instances.sh stop fra"
echo "  FRA logs:      ./scripts/manage-instances.sh logs fra"
echo ""

echo -e "${GREEN}✓ Deployment complete!${NC}"
