#!/bin/bash
# Quick Fix: Generate docker-compose.hostname.yml for custom hostname
# Resolves CORS errors when accessing via custom hostname

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

cd "$PROJECT_ROOT"

echo -e "${CYAN}╔════════════════════════════════════════════════════════════════╗${NC}"
echo -e "${CYAN}║                                                                ║${NC}"
echo -e "${CYAN}║     Fix CORS: Generate Custom Hostname Configuration          ║${NC}"
echo -e "${CYAN}║                                                                ║${NC}"
echo -e "${CYAN}╚════════════════════════════════════════════════════════════════╝${NC}"
echo ""

echo -e "${YELLOW}This script fixes CORS errors when using a custom hostname.${NC}"
echo ""
echo "Current issue:"
echo "  Access to fetch at https://localhost:4000/... from origin"
echo "  https://custom-url... has been blocked by CORS policy"
echo ""
echo "This happens because services are configured for localhost"
echo "but you're accessing via custom hostname."
echo ""

# Prompt for custom hostname
read -p "Enter your custom hostname (e.g., dive.mydomain.com): " CUSTOM_HOSTNAME

if [ -z "$CUSTOM_HOSTNAME" ]; then
    echo -e "${RED}Error: No hostname provided${NC}"
    exit 1
fi

if [ "$CUSTOM_HOSTNAME" = "localhost" ]; then
    echo -e "${YELLOW}Hostname is localhost - no custom configuration needed${NC}"
    exit 0
fi

echo ""
echo -e "${CYAN}Creating docker-compose.hostname.yml for: ${CUSTOM_HOSTNAME}${NC}"
echo ""

cat > docker-compose.hostname.yml << EOF
# Docker Compose Override for Custom Hostname
# Usage: docker-compose -f docker-compose.yml -f docker-compose.mkcert.yml -f docker-compose.hostname.yml up
# Generated by: $0

version: '3.8'

services:
  # Keycloak - Update hostname
  keycloak:
    environment:
      KC_HOSTNAME: ${CUSTOM_HOSTNAME}
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_ADMIN: ${CUSTOM_HOSTNAME}

  # Backend - Update CORS allowed origins
  backend:
    environment:
      NEXT_PUBLIC_BASE_URL: https://${CUSTOM_HOSTNAME}:3000
      FRONTEND_URL: https://${CUSTOM_HOSTNAME}:3000
      CORS_ALLOWED_ORIGINS: https://${CUSTOM_HOSTNAME}:3000,http://${CUSTOM_HOSTNAME}:3000

  # Frontend - Update public URLs
  nextjs:
    environment:
      NEXT_PUBLIC_API_URL: https://${CUSTOM_HOSTNAME}:4000
      NEXT_PUBLIC_BACKEND_URL: https://${CUSTOM_HOSTNAME}:4000
      NEXT_PUBLIC_BASE_URL: https://${CUSTOM_HOSTNAME}:3000
      NEXT_PUBLIC_KEYCLOAK_URL: https://${CUSTOM_HOSTNAME}:8443
      AUTH_URL: https://${CUSTOM_HOSTNAME}:3000
      NEXTAUTH_URL: https://${CUSTOM_HOSTNAME}:3000
      KEYCLOAK_BASE_URL: https://${CUSTOM_HOSTNAME}:8443
      KEYCLOAK_URL: https://${CUSTOM_HOSTNAME}:8443
EOF

echo -e "${GREEN}✓${NC} docker-compose.hostname.yml created"
echo ""

echo -e "${CYAN}Restarting services with new configuration...${NC}"
echo ""

# Stop services
echo "Stopping services..."
docker compose down

# Start with all three compose files
echo "Starting services with hostname override..."
if [ -f docker-compose.mkcert.yml ]; then
    docker compose -f docker-compose.yml -f docker-compose.mkcert.yml -f docker-compose.hostname.yml up -d
else
    docker compose -f docker-compose.yml -f docker-compose.hostname.yml up -d
fi

echo -e "${GREEN}✓${NC} Services restarted"
echo ""

echo -e "${CYAN}Waiting for services to be ready...${NC}"
sleep 10

echo ""
echo -e "${GREEN}✓${NC} Fix complete!"
echo ""
echo -e "${CYAN}Configuration Summary:${NC}"
echo "  Hostname: ${CUSTOM_HOSTNAME}"
echo "  Frontend: https://${CUSTOM_HOSTNAME}:3000"
echo "  Backend:  https://${CUSTOM_HOSTNAME}:4000"
echo "  Keycloak: https://${CUSTOM_HOSTNAME}:8443"
echo ""
echo -e "${CYAN}CORS Configuration:${NC}"
echo "  Backend now allows requests from:"
echo "    - https://${CUSTOM_HOSTNAME}:3000 ✓"
echo "    - http://${CUSTOM_HOSTNAME}:3000 ✓"
echo ""
echo -e "${YELLOW}Next steps:${NC}"
echo "  1. Access frontend at: https://${CUSTOM_HOSTNAME}:3000"
echo "  2. CORS errors should be resolved"
echo "  3. If still seeing localhost in URLs, clear browser cache"
echo ""
echo -e "${YELLOW}Remember:${NC}"
echo "  - Add to /etc/hosts: $(ip route get 1 2>/dev/null | awk '{print $7}' | head -1 || echo '<server-ip>') ${CUSTOM_HOSTNAME}"
echo "  - Clients need your mkcert Root CA: certs/mkcert/rootCA.pem"
echo ""

