#!/bin/bash
# =============================================================================
# DIVE V3 Database Migration Script
# =============================================================================
# Runs Drizzle migrations for NextAuth tables and other database schemas
#
# Usage:
#   ./scripts/migrate-db.sh [environment]
#
# Environment:
#   - local: Uses local Docker Compose database
#   - k8s: Uses Kubernetes database (requires kubectl access)
# =============================================================================

set -e

ENVIRONMENT="${1:-local}"

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m'

print_header() {
    echo -e "${BLUE}"
    echo "╔════════════════════════════════════════════════════════════╗"
    echo "║          DIVE V3 Database Migration                        ║"
    echo "╚════════════════════════════════════════════════════════════╝"
    echo -e "${NC}"
    echo "Environment: ${ENVIRONMENT}"
    echo ""
}

# Check if migrations directory exists
check_migrations() {
    if [ ! -d "frontend/drizzle/migrations" ]; then
        echo -e "${YELLOW}⚠️  Migrations directory not found${NC}"
        echo "Creating initial migration..."
        cd frontend
        npm run db:generate
        cd ..
    fi
}

# Run migrations locally (Docker Compose)
migrate_local() {
    echo -e "${BLUE}🔄 Running migrations (local)...${NC}"
    
    # Check if PostgreSQL is running
    if ! docker ps | grep -q dive-pilot-postgres; then
        echo -e "${RED}❌ PostgreSQL container not running${NC}"
        echo "Start with: ./dive up"
        exit 1
    fi
    
    # Run migrations via Docker
    docker exec -i dive-pilot-postgres psql -U postgres -d dive_v3_app << EOF
-- Check if migrations table exists
CREATE TABLE IF NOT EXISTS drizzle_migrations (
    id SERIAL PRIMARY KEY,
    hash TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT NOW()
);

-- Run migrations (example - adjust based on your Drizzle setup)
-- This is a placeholder - actual migrations should be generated by Drizzle
EOF
    
    # Run Drizzle migrations via frontend container or npm script
    if [ -f "frontend/package.json" ] && grep -q "db:migrate" frontend/package.json; then
        echo "Running Drizzle migrations..."
        cd frontend
        npm run db:migrate
        cd ..
    else
        echo -e "${YELLOW}⚠️  Drizzle migrations not configured${NC}"
        echo "Add 'db:migrate' script to frontend/package.json"
    fi
    
    echo -e "${GREEN}✅ Migrations complete${NC}"
}

# Run migrations in Kubernetes
migrate_k8s() {
    echo -e "${BLUE}🔄 Running migrations (Kubernetes)...${NC}"
    
    # Check kubectl access
    if ! kubectl cluster-info > /dev/null 2>&1; then
        echo -e "${RED}❌ Cannot access Kubernetes cluster${NC}"
        echo "Configure kubectl: gcloud container clusters get-credentials dive-v3-cluster --region us-east4"
        exit 1
    fi
    
    # Create migration job
    kubectl create job --from=cronjob/db-migrate db-migrate-manual-$(date +%s) -n dive-v3 || \
    kubectl run db-migrate-$(date +%s) \
        --image=gcr.io/dive25/dive-v3-frontend:latest \
        --restart=Never \
        --namespace=dive-v3 \
        --env="DATABASE_URL=\$(kubectl get secret database-credentials -n dive-v3 -o jsonpath='{.data.url}' | base64 -d)" \
        --command -- sh -c "cd /app && npm run db:migrate"
    
    echo -e "${GREEN}✅ Migration job created${NC}"
    echo "Check status: kubectl get jobs -n dive-v3"
}

# Main execution
main() {
    print_header
    
    check_migrations
    
    case $ENVIRONMENT in
        local)
            migrate_local
            ;;
        k8s|kubernetes)
            migrate_k8s
            ;;
        *)
            echo -e "${RED}❌ Unknown environment: ${ENVIRONMENT}${NC}"
            echo "Usage: $0 [local|k8s]"
            exit 1
            ;;
    esac
}

main



