#!/bin/bash
# Set or update custom hostname for DIVE V3 deployment

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

echo "======================================"
echo "DIVE V3 Custom Hostname Configuration"
echo "======================================"
echo ""

# Get current hostname from docker-compose.hostname.yml if it exists
CURRENT_HOSTNAME=""
if [ -f "$PROJECT_ROOT/docker-compose.hostname.yml" ]; then
    CURRENT_HOSTNAME=$(grep "KC_HOSTNAME:" "$PROJECT_ROOT/docker-compose.hostname.yml" | head -1 | awk '{print $2}' | tr -d '${}' | sed 's/CUSTOM_HOSTNAME//')
    if [ -n "$CURRENT_HOSTNAME" ]; then
        echo "Current custom hostname: $CURRENT_HOSTNAME"
        echo ""
    fi
fi

# Prompt for custom hostname
echo "Enter your custom hostname (e.g., dive.example.com, 192.168.1.100, dive.local):"
echo "Or press Enter to use 'localhost'"
read -r RAW_HOSTNAME

if [ -z "$RAW_HOSTNAME" ]; then
    CUSTOM_HOSTNAME="localhost"
    echo "Using localhost"
else
    # Sanitize hostname: remove protocol, port, paths
    CUSTOM_HOSTNAME=$(echo "$RAW_HOSTNAME" | sed -E 's|^https?://||' | sed -E 's|:[0-9]+.*$||' | sed -E 's|/.*$||')
    
    # Validate hostname format (basic check)
    if [[ ! "$CUSTOM_HOSTNAME" =~ ^[a-zA-Z0-9]([a-zA-Z0-9\-\.]*[a-zA-Z0-9])?$ ]]; then
        echo "❌ ERROR: Invalid hostname format: $RAW_HOSTNAME"
        echo "Hostname should be: domain.com, subdomain.domain.com, or IP address"
        echo "Should NOT include: https://, http://, ports (:8443), or paths (/admin)"
        exit 1
    fi
    
    if [ "$RAW_HOSTNAME" != "$CUSTOM_HOSTNAME" ]; then
        echo "⚠️  Sanitized your input:"
        echo "   You entered: $RAW_HOSTNAME"
        echo "   Using:       $CUSTOM_HOSTNAME"
        echo ""
    fi
    
    echo "Using custom hostname: $CUSTOM_HOSTNAME"
fi

echo ""
echo "Step 1: Creating docker-compose.hostname.yml..."

# Create docker-compose.hostname.yml
cat > "$PROJECT_ROOT/docker-compose.hostname.yml" << EOF
# Docker Compose overlay for custom hostname support
# This file is generated by set-custom-hostname.sh
# Usage: docker compose -f docker-compose.yml -f docker-compose.mkcert.yml -f docker-compose.hostname.yml up

version: '3.8'

services:
  # Keycloak - Update hostname for frontend and admin console
  keycloak:
    environment:
      KC_HOSTNAME: ${CUSTOM_HOSTNAME}
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_ADMIN: ${CUSTOM_HOSTNAME}

  # Backend - Update CORS allowed origins
  backend:
    environment:
      NEXT_PUBLIC_BASE_URL: https://${CUSTOM_HOSTNAME}:3000
      CORS_ALLOWED_ORIGINS: "https://${CUSTOM_HOSTNAME}:3000,https://${CUSTOM_HOSTNAME}:8443"

  # Frontend (Next.js) - Update Keycloak URL
  nextjs:
    environment:
      NEXTAUTH_URL: https://${CUSTOM_HOSTNAME}:3000
      NEXT_PUBLIC_KEYCLOAK_URL: https://${CUSTOM_HOSTNAME}:8443
      NEXT_PUBLIC_BACKEND_URL: https://${CUSTOM_HOSTNAME}:5000

  # MongoDB - No changes needed (internal only)
  mongodb:
    environment:
      # MongoDB uses internal hostname 'mongodb' for Docker network

  # OPA - Update bundle service URL
  opa:
    environment:
      OPA_BUNDLE_SERVICE_URL: https://${CUSTOM_HOSTNAME}:5000

  # KAS - Update Keycloak URL
  kas:
    environment:
      KEYCLOAK_URL: https://${CUSTOM_HOSTNAME}:8443
EOF

echo "✓ Created docker-compose.hostname.yml"

echo ""
echo "Step 2: Applying Terraform changes..."
cd "$PROJECT_ROOT/terraform"

# Initialize if needed
if [ ! -d ".terraform" ]; then
    echo "Initializing Terraform..."
    terraform init
fi

# Apply with custom hostname variables
echo "Running terraform apply with:"
echo "  - keycloak_url=https://${CUSTOM_HOSTNAME}:8443"
echo "  - app_url=https://${CUSTOM_HOSTNAME}:3000"
echo "  - backend_url=https://${CUSTOM_HOSTNAME}:5000"
echo ""

terraform apply \
  -var="keycloak_url=https://${CUSTOM_HOSTNAME}:8443" \
  -var="app_url=https://${CUSTOM_HOSTNAME}:3000" \
  -var="backend_url=https://${CUSTOM_HOSTNAME}:5000" \
  -auto-approve

echo ""
echo "✓ Terraform changes applied"

echo ""
echo "Step 3: Restarting services with new hostname..."
cd "$PROJECT_ROOT"

# Stop all services
echo "Stopping services..."
docker compose down

# Start with all overlays
echo "Starting services with custom hostname..."
docker compose \
  -f docker-compose.yml \
  -f docker-compose.mkcert.yml \
  -f docker-compose.hostname.yml \
  up -d

echo ""
echo "Waiting for services to start (60 seconds)..."
sleep 60

echo ""
echo "====================================="
echo "✅ Custom Hostname Configuration Complete!"
echo "====================================="
echo ""
echo "Your services are now accessible at:"
echo "  • Frontend:     https://${CUSTOM_HOSTNAME}:3000"
echo "  • Backend API:  https://${CUSTOM_HOSTNAME}:5000"
echo "  • Keycloak:     https://${CUSTOM_HOSTNAME}:8443"
echo "  • Admin Console: https://${CUSTOM_HOSTNAME}:8443/admin"
echo ""
echo "Important Notes:"
echo "  1. DNS/Hosts: Ensure '${CUSTOM_HOSTNAME}' resolves to this server"
echo "  2. Certificates: mkcert certificates include '${CUSTOM_HOSTNAME}'"
echo "  3. Terraform: All redirect URIs now use '${CUSTOM_HOSTNAME}'"
echo "  4. Admin Console: Will stay on '${CUSTOM_HOSTNAME}' (no localhost rollback)"
echo ""
echo "To change hostname again, run: ./scripts/set-custom-hostname.sh"
echo ""

