#!/bin/bash
#
# DIVE V3 - Environment Synchronization Script
#
# This script ensures all configuration formats are synchronized from the
# single source of truth: .env.secrets
#
# Why this is needed:
# - .env.secrets uses shell format (export VAR=value) for sourcing in bash
# - Docker Compose reads .env (without 'export') automatically
# - Terraform reads TF_VAR_* from environment or .auto.tfvars
#
# Usage:
#   ./scripts/sync-env.sh
#
# This should be run:
# - After editing .env.secrets
# - Before running docker compose up
# - The start.sh script calls this automatically
#

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

cd "$PROJECT_ROOT"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Check if .env.secrets exists
if [[ ! -f .env.secrets ]]; then
  echo -e "${RED}Error: .env.secrets not found${NC}"
  echo "Create it first:"
  echo "  cp .env.secrets.example .env.secrets"
  echo "  # Edit .env.secrets with your passwords"
  exit 1
fi

# Source the secrets file to get variables
source .env.secrets

# Validate required variables are set
REQUIRED_VARS=(
  "DIVE_MASTER_PASSWORD"
  "KEYCLOAK_ADMIN_USERNAME"
  "KEYCLOAK_ADMIN_PASSWORD"
  "POSTGRES_PASSWORD"
  "MONGO_INITDB_ROOT_PASSWORD"
)

MISSING=0
for var in "${REQUIRED_VARS[@]}"; do
  if [[ -z "${!var}" ]]; then
    echo -e "${RED}Missing required variable: $var${NC}"
    MISSING=1
  fi
done

if [[ $MISSING -eq 1 ]]; then
  echo -e "${RED}Please set all required variables in .env.secrets${NC}"
  exit 1
fi

# Generate Docker Compose .env file
cat > .env << EOF
# =============================================================================
# DIVE V3 - Docker Compose Environment File
# =============================================================================
# AUTO-GENERATED by scripts/sync-env.sh - DO NOT EDIT DIRECTLY
# 
# To change values, edit .env.secrets and run:
#   ./scripts/sync-env.sh
#
# Generated: $(date -Iseconds)
# =============================================================================

# Master Password (all services use this in dev/pilot)
DIVE_MASTER_PASSWORD=${DIVE_MASTER_PASSWORD}

# Keycloak Admin
KEYCLOAK_ADMIN_USERNAME=${KEYCLOAK_ADMIN_USERNAME}
KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}

# PostgreSQL
POSTGRES_USER=postgres
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

# MongoDB
MONGO_INITDB_ROOT_USERNAME=admin
MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}

# Redis (if auth enabled)
REDIS_PASSWORD=${REDIS_PASSWORD:-${DIVE_MASTER_PASSWORD}}

# NextAuth Secret
AUTH_SECRET=${AUTH_SECRET:-dive-v3-pilot-auth-secret-2025}

# Keycloak Client Secrets (per instance)
USA_KEYCLOAK_CLIENT_SECRET=${USA_KEYCLOAK_CLIENT_SECRET:-8AcfbgtdNIZp3tbrcmc2voiUfxNb8d6L}
FRA_KEYCLOAK_CLIENT_SECRET=${FRA_KEYCLOAK_CLIENT_SECRET:-FRA_CLIENT_SECRET_HERE}
DEU_KEYCLOAK_CLIENT_SECRET=${DEU_KEYCLOAK_CLIENT_SECRET:-DwomOUe3n0fxipPhGaPu17b1xsf8nTSi}

EOF

echo -e "${GREEN}✓ Generated .env (Docker Compose format)${NC}"

# Generate Terraform auto.tfvars
cat > terraform/terraform.auto.tfvars << EOF
# =============================================================================
# DIVE V3 - Terraform Auto Variables
# =============================================================================
# AUTO-GENERATED by scripts/sync-env.sh - DO NOT EDIT DIRECTLY
#
# To change values, edit .env.secrets and run:
#   ./scripts/sync-env.sh
#
# Generated: $(date -Iseconds)
# =============================================================================

keycloak_admin_username = "${KEYCLOAK_ADMIN_USERNAME}"
keycloak_admin_password = "${KEYCLOAK_ADMIN_PASSWORD}"

EOF

echo -e "${GREEN}✓ Generated terraform/terraform.auto.tfvars${NC}"

# Verify the generated .env can be read by docker compose
COMPOSE_CHECK=$(docker compose config 2>&1 | grep -c "KEYCLOAK_ADMIN_PASSWORD" || true)
if [[ "$COMPOSE_CHECK" -gt 0 ]]; then
  echo -e "${GREEN}✓ Docker Compose can read .env${NC}"
else
  echo -e "${YELLOW}⚠ Docker Compose may not be reading .env correctly${NC}"
fi

echo ""
echo -e "${GREEN}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}  ✅ Environment Synchronized${NC}"
echo -e "${GREEN}═══════════════════════════════════════════════════════════════${NC}"
echo ""
echo "Files updated:"
echo "  - .env (Docker Compose format)"
echo "  - terraform/terraform.auto.tfvars"
echo ""
echo "Current configuration:"
echo "  - Admin Password: ${KEYCLOAK_ADMIN_PASSWORD}"
echo "  - Database Password: ${POSTGRES_PASSWORD}"
echo ""
echo "Next steps:"
echo "  1. Run: ./scripts/start.sh"
echo "  2. Or manually: docker compose up -d"
echo ""

