<?php

/**
 * DIVE V3 - Spain SAML IdP Metadata (Hosted)
 * This file defines the Spanish Defense Ministry SAML 2.0 IdP
 */

// The index of the array is the entity ID of this IdP
$metadata['http://localhost:9443/simplesaml/saml2/idp/metadata.php'] = [
    // The hostname for this IdP - use __DEFAULT__ to match all hostnames
    'host' => '__DEFAULT__',

    // X.509 certificate and private key
    'certificate' => 'server.crt',
    'privatekey' => 'server.pem',

    // Authentication source
    'auth' => 'example-userpass',

    // NameID format
    'NameIDFormat' => [
        'urn:oasis:names:tc:SAML:2.0:nameid-format:transient',
        'urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress',
        'urn:oasis:names:tc:SAML:2.0:nameid-format:persistent',
    ],

    // Attribute mapping (Spanish attributes → SAML attributes)
    'authproc' => [
        // Convert internal PHP UTF-8 to output (all attributes)
        1 => ['class' => 'core:AttributeMap', 'name2oid'],
        
        // Map Spanish military attributes to standard SAML attributes
        10 => [
            'class' => 'core:AttributeAdd',
            'eduPersonPrincipalName' => ['%uid%'],
        ],
        
        // Add additional attributes for DIVE federation
        20 => [
            'class' => 'core:PHP',
            'code' => '
                // Map Spanish clearance levels to DIVE clearance
                if (isset($attributes["nivelSeguridad"])) {
                    $spanishLevel = $attributes["nivelSeguridad"][0];
                    $diveClearance = "";
                    
                    switch ($spanishLevel) {
                        case "SECRETO":
                            $diveClearance = "TOP_SECRET";
                            break;
                        case "CONFIDENCIAL-DEFENSA":
                        case "CONFIDENCIAL":
                            $diveClearance = $spanishLevel === "CONFIDENCIAL-DEFENSA" ? "SECRET" : "CONFIDENTIAL";
                            break;
                        case "NO-CLASIFICADO":
                            $diveClearance = "UNCLASSIFIED";
                            break;
                        default:
                            $diveClearance = "UNCLASSIFIED";
                    }
                    
                    $attributes["clearance"] = [$diveClearance];
                }
                
                // Normalize country code
                if (isset($attributes["paisAfiliacion"])) {
                    $attributes["countryOfAffiliation"] = $attributes["paisAfiliacion"];
                }
                
                // Normalize COI tags
                if (isset($attributes["grupoInteresCompartido"])) {
                    $attributes["acpCOI"] = $attributes["grupoInteresCompartido"];
                }
                
                // Set uniqueID from email
                if (isset($attributes["uid"])) {
                    $attributes["uniqueID"] = $attributes["uid"];
                }
            ',
        ],
        
        // Convert to SAML 2.0 attributes
        90 => ['class' => 'core:AttributeMap', 'oid2name'],
    ],

    // Note: Endpoints (SingleSignOnService, SingleLogoutService) are automatically
    // generated by SimpleSAMLphp based on baseurlpath configuration
];


